//Generated by TurboLink CodeGenerator, do not edit!
#include "CharacterService_Private.h"

void UCharacterServiceGetCharactersLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroCharacterCharactersDetails& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnGetCharactersResponse.RemoveDynamic(this, &UCharacterServiceGetCharactersLambdaWrapper::OnResponse);
}

void UCharacterServiceGetCharacterLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroCharacterCharacterDetails& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnGetCharacterResponse.RemoveDynamic(this, &UCharacterServiceGetCharacterLambdaWrapper::OnResponse);
}

void UCharacterServiceCreateCharacterLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroCharacterCharacterDetails& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnCreateCharacterResponse.RemoveDynamic(this, &UCharacterServiceCreateCharacterLambdaWrapper::OnResponse);
}

void UCharacterServiceDeleteCharacterLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnDeleteCharacterResponse.RemoveDynamic(this, &UCharacterServiceDeleteCharacterLambdaWrapper::OnResponse);
}

void UCharacterServiceGetAllCharactersForUserLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroCharacterCharactersDetails& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnGetAllCharactersForUserResponse.RemoveDynamic(this, &UCharacterServiceGetAllCharactersForUserLambdaWrapper::OnResponse);
}

void UCharacterServiceEditCharacterLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnEditCharacterResponse.RemoveDynamic(this, &UCharacterServiceEditCharacterLambdaWrapper::OnResponse);
}

void UCharacterServiceAddCharacterPlayTimeLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroCharacterPlayTimeResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnAddCharacterPlayTimeResponse.RemoveDynamic(this, &UCharacterServiceAddCharacterPlayTimeLambdaWrapper::OnResponse);
}

void UCharacterServiceGetInventoryLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroCharacterInventory& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnGetInventoryResponse.RemoveDynamic(this, &UCharacterServiceGetInventoryLambdaWrapper::OnResponse);
}

void UCharacterServiceSetInventoryLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnSetInventoryResponse.RemoveDynamic(this, &UCharacterServiceSetInventoryLambdaWrapper::OnResponse);
}

