//Generated by TurboLink CodeGenerator, do not edit!
#include "CharacterContext.h"
#include "SSroCharacter/CharacterClient.h"
#include "CharacterService_Private.h"
#include "CharacterMarshaling.h"
#include "SGoogleApi/AnnotationsMarshaling.h"
#include "SGoogleProtobuf/EmptyMarshaling.h"
#include "SSro/GlobalsMarshaling.h"
#include "SSroGamebackend/ServermanagerMarshaling.h"
#include "TurboLinkGrpcManager.h"

GrpcContext_CharacterService_GetCharacters::GrpcContext_CharacterService_GetCharacters(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_CharacterService_GetCharacters::Call(const FGrpcGoogleProtobufEmpty& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::google::protobuf::Empty rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UCharacterService* service = (UCharacterService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncGetCharacters(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_CharacterService_GetCharacters::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::sro::character::CharactersDetails* _RpcResponse) 
		{
			UCharacterServiceClient* client = (UCharacterServiceClient*)(this->Client);
			if (!(client->OnGetCharactersResponse.IsBound())) return;

			FGrpcSroCharacterCharactersDetails response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnGetCharactersResponse.Broadcast(Handle, _Result, response);
		}
	);
}

GrpcContext_CharacterService_GetCharacter::GrpcContext_CharacterService_GetCharacter(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_CharacterService_GetCharacter::Call(const FGrpcSroCharacterCharacterTarget& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::sro::character::CharacterTarget rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UCharacterService* service = (UCharacterService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncGetCharacter(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_CharacterService_GetCharacter::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::sro::character::CharacterDetails* _RpcResponse) 
		{
			UCharacterServiceClient* client = (UCharacterServiceClient*)(this->Client);
			if (!(client->OnGetCharacterResponse.IsBound())) return;

			FGrpcSroCharacterCharacterDetails response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnGetCharacterResponse.Broadcast(Handle, _Result, response);
		}
	);
}

GrpcContext_CharacterService_CreateCharacter::GrpcContext_CharacterService_CreateCharacter(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_CharacterService_CreateCharacter::Call(const FGrpcSroCharacterCreateCharacterRequest& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::sro::character::CreateCharacterRequest rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UCharacterService* service = (UCharacterService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncCreateCharacter(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_CharacterService_CreateCharacter::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::sro::character::CharacterDetails* _RpcResponse) 
		{
			UCharacterServiceClient* client = (UCharacterServiceClient*)(this->Client);
			if (!(client->OnCreateCharacterResponse.IsBound())) return;

			FGrpcSroCharacterCharacterDetails response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnCreateCharacterResponse.Broadcast(Handle, _Result, response);
		}
	);
}

GrpcContext_CharacterService_DeleteCharacter::GrpcContext_CharacterService_DeleteCharacter(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_CharacterService_DeleteCharacter::Call(const FGrpcSroCharacterCharacterTarget& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::sro::character::CharacterTarget rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UCharacterService* service = (UCharacterService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncDeleteCharacter(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_CharacterService_DeleteCharacter::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::google::protobuf::Empty* _RpcResponse) 
		{
			UCharacterServiceClient* client = (UCharacterServiceClient*)(this->Client);
			if (!(client->OnDeleteCharacterResponse.IsBound())) return;

			FGrpcGoogleProtobufEmpty response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnDeleteCharacterResponse.Broadcast(Handle, _Result, response);
		}
	);
}

GrpcContext_CharacterService_GetAllCharactersForUser::GrpcContext_CharacterService_GetAllCharactersForUser(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_CharacterService_GetAllCharactersForUser::Call(const FGrpcSroUserTarget& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::sro::UserTarget rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UCharacterService* service = (UCharacterService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncGetAllCharactersForUser(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_CharacterService_GetAllCharactersForUser::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::sro::character::CharactersDetails* _RpcResponse) 
		{
			UCharacterServiceClient* client = (UCharacterServiceClient*)(this->Client);
			if (!(client->OnGetAllCharactersForUserResponse.IsBound())) return;

			FGrpcSroCharacterCharactersDetails response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnGetAllCharactersForUserResponse.Broadcast(Handle, _Result, response);
		}
	);
}

GrpcContext_CharacterService_EditCharacter::GrpcContext_CharacterService_EditCharacter(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_CharacterService_EditCharacter::Call(const FGrpcSroCharacterEditCharacterRequest& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::sro::character::EditCharacterRequest rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UCharacterService* service = (UCharacterService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncEditCharacter(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_CharacterService_EditCharacter::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::google::protobuf::Empty* _RpcResponse) 
		{
			UCharacterServiceClient* client = (UCharacterServiceClient*)(this->Client);
			if (!(client->OnEditCharacterResponse.IsBound())) return;

			FGrpcGoogleProtobufEmpty response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnEditCharacterResponse.Broadcast(Handle, _Result, response);
		}
	);
}

GrpcContext_CharacterService_AddCharacterPlayTime::GrpcContext_CharacterService_AddCharacterPlayTime(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_CharacterService_AddCharacterPlayTime::Call(const FGrpcSroCharacterAddPlayTimeRequest& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::sro::character::AddPlayTimeRequest rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UCharacterService* service = (UCharacterService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncAddCharacterPlayTime(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_CharacterService_AddCharacterPlayTime::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::sro::character::PlayTimeResponse* _RpcResponse) 
		{
			UCharacterServiceClient* client = (UCharacterServiceClient*)(this->Client);
			if (!(client->OnAddCharacterPlayTimeResponse.IsBound())) return;

			FGrpcSroCharacterPlayTimeResponse response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnAddCharacterPlayTimeResponse.Broadcast(Handle, _Result, response);
		}
	);
}

GrpcContext_CharacterService_GetInventory::GrpcContext_CharacterService_GetInventory(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_CharacterService_GetInventory::Call(const FGrpcSroCharacterCharacterTarget& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::sro::character::CharacterTarget rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UCharacterService* service = (UCharacterService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncGetInventory(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_CharacterService_GetInventory::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::sro::character::Inventory* _RpcResponse) 
		{
			UCharacterServiceClient* client = (UCharacterServiceClient*)(this->Client);
			if (!(client->OnGetInventoryResponse.IsBound())) return;

			FGrpcSroCharacterInventory response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnGetInventoryResponse.Broadcast(Handle, _Result, response);
		}
	);
}

GrpcContext_CharacterService_SetInventory::GrpcContext_CharacterService_SetInventory(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_CharacterService_SetInventory::Call(const FGrpcSroCharacterUpdateInventoryRequest& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::sro::character::UpdateInventoryRequest rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UCharacterService* service = (UCharacterService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncSetInventory(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_CharacterService_SetInventory::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::google::protobuf::Empty* _RpcResponse) 
		{
			UCharacterServiceClient* client = (UCharacterServiceClient*)(this->Client);
			if (!(client->OnSetInventoryResponse.IsBound())) return;

			FGrpcGoogleProtobufEmpty response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnSetInventoryResponse.Broadcast(Handle, _Result, response);
		}
	);
}
