// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sro/gamebackend/connection.proto
#ifndef GRPC_sro_2fgamebackend_2fconnection_2eproto__INCLUDED
#define GRPC_sro_2fgamebackend_2fconnection_2eproto__INCLUDED

#include "sro/gamebackend/connection.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace sro {
namespace gamebackend {

class ConnectionService final {
 public:
  static constexpr char const* service_full_name() {
    return "sro.gamebackend.ConnectionService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ConnectGameServer(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::sro::gamebackend::ConnectGameServerResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectGameServerResponse>> AsyncConnectGameServer(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectGameServerResponse>>(AsyncConnectGameServerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectGameServerResponse>> PrepareAsyncConnectGameServer(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectGameServerResponse>>(PrepareAsyncConnectGameServerRaw(context, request, cq));
    }
    virtual ::grpc::Status VerifyConnect(::grpc::ClientContext* context, const ::sro::gamebackend::VerifyConnectRequest& request, ::sro::character::CharacterDetails* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::character::CharacterDetails>> AsyncVerifyConnect(::grpc::ClientContext* context, const ::sro::gamebackend::VerifyConnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::character::CharacterDetails>>(AsyncVerifyConnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::character::CharacterDetails>> PrepareAsyncVerifyConnect(::grpc::ClientContext* context, const ::sro::gamebackend::VerifyConnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::character::CharacterDetails>>(PrepareAsyncVerifyConnectRaw(context, request, cq));
    }
    virtual ::grpc::Status TransferPlayer(::grpc::ClientContext* context, const ::sro::gamebackend::TransferPlayerRequest& request, ::sro::gamebackend::ConnectGameServerResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectGameServerResponse>> AsyncTransferPlayer(::grpc::ClientContext* context, const ::sro::gamebackend::TransferPlayerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectGameServerResponse>>(AsyncTransferPlayerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectGameServerResponse>> PrepareAsyncTransferPlayer(::grpc::ClientContext* context, const ::sro::gamebackend::TransferPlayerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectGameServerResponse>>(PrepareAsyncTransferPlayerRaw(context, request, cq));
    }
    virtual ::grpc::Status IsPlaying(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::sro::gamebackend::ConnectionStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectionStatus>> AsyncIsPlaying(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectionStatus>>(AsyncIsPlayingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectionStatus>> PrepareAsyncIsPlaying(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectionStatus>>(PrepareAsyncIsPlayingRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ConnectGameServer(::grpc::ClientContext* context, const ::sro::character::CharacterTarget* request, ::sro::gamebackend::ConnectGameServerResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ConnectGameServer(::grpc::ClientContext* context, const ::sro::character::CharacterTarget* request, ::sro::gamebackend::ConnectGameServerResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void VerifyConnect(::grpc::ClientContext* context, const ::sro::gamebackend::VerifyConnectRequest* request, ::sro::character::CharacterDetails* response, std::function<void(::grpc::Status)>) = 0;
      virtual void VerifyConnect(::grpc::ClientContext* context, const ::sro::gamebackend::VerifyConnectRequest* request, ::sro::character::CharacterDetails* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void TransferPlayer(::grpc::ClientContext* context, const ::sro::gamebackend::TransferPlayerRequest* request, ::sro::gamebackend::ConnectGameServerResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void TransferPlayer(::grpc::ClientContext* context, const ::sro::gamebackend::TransferPlayerRequest* request, ::sro::gamebackend::ConnectGameServerResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void IsPlaying(::grpc::ClientContext* context, const ::sro::character::CharacterTarget* request, ::sro::gamebackend::ConnectionStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void IsPlaying(::grpc::ClientContext* context, const ::sro::character::CharacterTarget* request, ::sro::gamebackend::ConnectionStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectGameServerResponse>* AsyncConnectGameServerRaw(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectGameServerResponse>* PrepareAsyncConnectGameServerRaw(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sro::character::CharacterDetails>* AsyncVerifyConnectRaw(::grpc::ClientContext* context, const ::sro::gamebackend::VerifyConnectRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sro::character::CharacterDetails>* PrepareAsyncVerifyConnectRaw(::grpc::ClientContext* context, const ::sro::gamebackend::VerifyConnectRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectGameServerResponse>* AsyncTransferPlayerRaw(::grpc::ClientContext* context, const ::sro::gamebackend::TransferPlayerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectGameServerResponse>* PrepareAsyncTransferPlayerRaw(::grpc::ClientContext* context, const ::sro::gamebackend::TransferPlayerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectionStatus>* AsyncIsPlayingRaw(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sro::gamebackend::ConnectionStatus>* PrepareAsyncIsPlayingRaw(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ConnectGameServer(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::sro::gamebackend::ConnectGameServerResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectGameServerResponse>> AsyncConnectGameServer(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectGameServerResponse>>(AsyncConnectGameServerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectGameServerResponse>> PrepareAsyncConnectGameServer(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectGameServerResponse>>(PrepareAsyncConnectGameServerRaw(context, request, cq));
    }
    ::grpc::Status VerifyConnect(::grpc::ClientContext* context, const ::sro::gamebackend::VerifyConnectRequest& request, ::sro::character::CharacterDetails* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::character::CharacterDetails>> AsyncVerifyConnect(::grpc::ClientContext* context, const ::sro::gamebackend::VerifyConnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::character::CharacterDetails>>(AsyncVerifyConnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::character::CharacterDetails>> PrepareAsyncVerifyConnect(::grpc::ClientContext* context, const ::sro::gamebackend::VerifyConnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::character::CharacterDetails>>(PrepareAsyncVerifyConnectRaw(context, request, cq));
    }
    ::grpc::Status TransferPlayer(::grpc::ClientContext* context, const ::sro::gamebackend::TransferPlayerRequest& request, ::sro::gamebackend::ConnectGameServerResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectGameServerResponse>> AsyncTransferPlayer(::grpc::ClientContext* context, const ::sro::gamebackend::TransferPlayerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectGameServerResponse>>(AsyncTransferPlayerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectGameServerResponse>> PrepareAsyncTransferPlayer(::grpc::ClientContext* context, const ::sro::gamebackend::TransferPlayerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectGameServerResponse>>(PrepareAsyncTransferPlayerRaw(context, request, cq));
    }
    ::grpc::Status IsPlaying(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::sro::gamebackend::ConnectionStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectionStatus>> AsyncIsPlaying(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectionStatus>>(AsyncIsPlayingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectionStatus>> PrepareAsyncIsPlaying(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectionStatus>>(PrepareAsyncIsPlayingRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ConnectGameServer(::grpc::ClientContext* context, const ::sro::character::CharacterTarget* request, ::sro::gamebackend::ConnectGameServerResponse* response, std::function<void(::grpc::Status)>) override;
      void ConnectGameServer(::grpc::ClientContext* context, const ::sro::character::CharacterTarget* request, ::sro::gamebackend::ConnectGameServerResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void VerifyConnect(::grpc::ClientContext* context, const ::sro::gamebackend::VerifyConnectRequest* request, ::sro::character::CharacterDetails* response, std::function<void(::grpc::Status)>) override;
      void VerifyConnect(::grpc::ClientContext* context, const ::sro::gamebackend::VerifyConnectRequest* request, ::sro::character::CharacterDetails* response, ::grpc::ClientUnaryReactor* reactor) override;
      void TransferPlayer(::grpc::ClientContext* context, const ::sro::gamebackend::TransferPlayerRequest* request, ::sro::gamebackend::ConnectGameServerResponse* response, std::function<void(::grpc::Status)>) override;
      void TransferPlayer(::grpc::ClientContext* context, const ::sro::gamebackend::TransferPlayerRequest* request, ::sro::gamebackend::ConnectGameServerResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void IsPlaying(::grpc::ClientContext* context, const ::sro::character::CharacterTarget* request, ::sro::gamebackend::ConnectionStatus* response, std::function<void(::grpc::Status)>) override;
      void IsPlaying(::grpc::ClientContext* context, const ::sro::character::CharacterTarget* request, ::sro::gamebackend::ConnectionStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectGameServerResponse>* AsyncConnectGameServerRaw(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectGameServerResponse>* PrepareAsyncConnectGameServerRaw(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sro::character::CharacterDetails>* AsyncVerifyConnectRaw(::grpc::ClientContext* context, const ::sro::gamebackend::VerifyConnectRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sro::character::CharacterDetails>* PrepareAsyncVerifyConnectRaw(::grpc::ClientContext* context, const ::sro::gamebackend::VerifyConnectRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectGameServerResponse>* AsyncTransferPlayerRaw(::grpc::ClientContext* context, const ::sro::gamebackend::TransferPlayerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectGameServerResponse>* PrepareAsyncTransferPlayerRaw(::grpc::ClientContext* context, const ::sro::gamebackend::TransferPlayerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectionStatus>* AsyncIsPlayingRaw(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectionStatus>* PrepareAsyncIsPlayingRaw(::grpc::ClientContext* context, const ::sro::character::CharacterTarget& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ConnectGameServer_;
    const ::grpc::internal::RpcMethod rpcmethod_VerifyConnect_;
    const ::grpc::internal::RpcMethod rpcmethod_TransferPlayer_;
    const ::grpc::internal::RpcMethod rpcmethod_IsPlaying_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ConnectGameServer(::grpc::ServerContext* context, const ::sro::character::CharacterTarget* request, ::sro::gamebackend::ConnectGameServerResponse* response);
    virtual ::grpc::Status VerifyConnect(::grpc::ServerContext* context, const ::sro::gamebackend::VerifyConnectRequest* request, ::sro::character::CharacterDetails* response);
    virtual ::grpc::Status TransferPlayer(::grpc::ServerContext* context, const ::sro::gamebackend::TransferPlayerRequest* request, ::sro::gamebackend::ConnectGameServerResponse* response);
    virtual ::grpc::Status IsPlaying(::grpc::ServerContext* context, const ::sro::character::CharacterTarget* request, ::sro::gamebackend::ConnectionStatus* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ConnectGameServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ConnectGameServer() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ConnectGameServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConnectGameServer(::grpc::ServerContext* /*context*/, const ::sro::character::CharacterTarget* /*request*/, ::sro::gamebackend::ConnectGameServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConnectGameServer(::grpc::ServerContext* context, ::sro::character::CharacterTarget* request, ::grpc::ServerAsyncResponseWriter< ::sro::gamebackend::ConnectGameServerResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_VerifyConnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_VerifyConnect() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_VerifyConnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyConnect(::grpc::ServerContext* /*context*/, const ::sro::gamebackend::VerifyConnectRequest* /*request*/, ::sro::character::CharacterDetails* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifyConnect(::grpc::ServerContext* context, ::sro::gamebackend::VerifyConnectRequest* request, ::grpc::ServerAsyncResponseWriter< ::sro::character::CharacterDetails>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_TransferPlayer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_TransferPlayer() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_TransferPlayer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TransferPlayer(::grpc::ServerContext* /*context*/, const ::sro::gamebackend::TransferPlayerRequest* /*request*/, ::sro::gamebackend::ConnectGameServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTransferPlayer(::grpc::ServerContext* context, ::sro::gamebackend::TransferPlayerRequest* request, ::grpc::ServerAsyncResponseWriter< ::sro::gamebackend::ConnectGameServerResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_IsPlaying : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_IsPlaying() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_IsPlaying() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsPlaying(::grpc::ServerContext* /*context*/, const ::sro::character::CharacterTarget* /*request*/, ::sro::gamebackend::ConnectionStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIsPlaying(::grpc::ServerContext* context, ::sro::character::CharacterTarget* request, ::grpc::ServerAsyncResponseWriter< ::sro::gamebackend::ConnectionStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ConnectGameServer<WithAsyncMethod_VerifyConnect<WithAsyncMethod_TransferPlayer<WithAsyncMethod_IsPlaying<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ConnectGameServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ConnectGameServer() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::sro::character::CharacterTarget, ::sro::gamebackend::ConnectGameServerResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sro::character::CharacterTarget* request, ::sro::gamebackend::ConnectGameServerResponse* response) { return this->ConnectGameServer(context, request, response); }));}
    void SetMessageAllocatorFor_ConnectGameServer(
        ::grpc::MessageAllocator< ::sro::character::CharacterTarget, ::sro::gamebackend::ConnectGameServerResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sro::character::CharacterTarget, ::sro::gamebackend::ConnectGameServerResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ConnectGameServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConnectGameServer(::grpc::ServerContext* /*context*/, const ::sro::character::CharacterTarget* /*request*/, ::sro::gamebackend::ConnectGameServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ConnectGameServer(
      ::grpc::CallbackServerContext* /*context*/, const ::sro::character::CharacterTarget* /*request*/, ::sro::gamebackend::ConnectGameServerResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_VerifyConnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_VerifyConnect() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::sro::gamebackend::VerifyConnectRequest, ::sro::character::CharacterDetails>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sro::gamebackend::VerifyConnectRequest* request, ::sro::character::CharacterDetails* response) { return this->VerifyConnect(context, request, response); }));}
    void SetMessageAllocatorFor_VerifyConnect(
        ::grpc::MessageAllocator< ::sro::gamebackend::VerifyConnectRequest, ::sro::character::CharacterDetails>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sro::gamebackend::VerifyConnectRequest, ::sro::character::CharacterDetails>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_VerifyConnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyConnect(::grpc::ServerContext* /*context*/, const ::sro::gamebackend::VerifyConnectRequest* /*request*/, ::sro::character::CharacterDetails* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VerifyConnect(
      ::grpc::CallbackServerContext* /*context*/, const ::sro::gamebackend::VerifyConnectRequest* /*request*/, ::sro::character::CharacterDetails* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_TransferPlayer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_TransferPlayer() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::sro::gamebackend::TransferPlayerRequest, ::sro::gamebackend::ConnectGameServerResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sro::gamebackend::TransferPlayerRequest* request, ::sro::gamebackend::ConnectGameServerResponse* response) { return this->TransferPlayer(context, request, response); }));}
    void SetMessageAllocatorFor_TransferPlayer(
        ::grpc::MessageAllocator< ::sro::gamebackend::TransferPlayerRequest, ::sro::gamebackend::ConnectGameServerResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sro::gamebackend::TransferPlayerRequest, ::sro::gamebackend::ConnectGameServerResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_TransferPlayer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TransferPlayer(::grpc::ServerContext* /*context*/, const ::sro::gamebackend::TransferPlayerRequest* /*request*/, ::sro::gamebackend::ConnectGameServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TransferPlayer(
      ::grpc::CallbackServerContext* /*context*/, const ::sro::gamebackend::TransferPlayerRequest* /*request*/, ::sro::gamebackend::ConnectGameServerResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_IsPlaying : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_IsPlaying() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::sro::character::CharacterTarget, ::sro::gamebackend::ConnectionStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sro::character::CharacterTarget* request, ::sro::gamebackend::ConnectionStatus* response) { return this->IsPlaying(context, request, response); }));}
    void SetMessageAllocatorFor_IsPlaying(
        ::grpc::MessageAllocator< ::sro::character::CharacterTarget, ::sro::gamebackend::ConnectionStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sro::character::CharacterTarget, ::sro::gamebackend::ConnectionStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_IsPlaying() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsPlaying(::grpc::ServerContext* /*context*/, const ::sro::character::CharacterTarget* /*request*/, ::sro::gamebackend::ConnectionStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* IsPlaying(
      ::grpc::CallbackServerContext* /*context*/, const ::sro::character::CharacterTarget* /*request*/, ::sro::gamebackend::ConnectionStatus* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ConnectGameServer<WithCallbackMethod_VerifyConnect<WithCallbackMethod_TransferPlayer<WithCallbackMethod_IsPlaying<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ConnectGameServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ConnectGameServer() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ConnectGameServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConnectGameServer(::grpc::ServerContext* /*context*/, const ::sro::character::CharacterTarget* /*request*/, ::sro::gamebackend::ConnectGameServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_VerifyConnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_VerifyConnect() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_VerifyConnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyConnect(::grpc::ServerContext* /*context*/, const ::sro::gamebackend::VerifyConnectRequest* /*request*/, ::sro::character::CharacterDetails* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_TransferPlayer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_TransferPlayer() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_TransferPlayer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TransferPlayer(::grpc::ServerContext* /*context*/, const ::sro::gamebackend::TransferPlayerRequest* /*request*/, ::sro::gamebackend::ConnectGameServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_IsPlaying : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_IsPlaying() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_IsPlaying() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsPlaying(::grpc::ServerContext* /*context*/, const ::sro::character::CharacterTarget* /*request*/, ::sro::gamebackend::ConnectionStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ConnectGameServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ConnectGameServer() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ConnectGameServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConnectGameServer(::grpc::ServerContext* /*context*/, const ::sro::character::CharacterTarget* /*request*/, ::sro::gamebackend::ConnectGameServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConnectGameServer(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_VerifyConnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_VerifyConnect() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_VerifyConnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyConnect(::grpc::ServerContext* /*context*/, const ::sro::gamebackend::VerifyConnectRequest* /*request*/, ::sro::character::CharacterDetails* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifyConnect(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_TransferPlayer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_TransferPlayer() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_TransferPlayer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TransferPlayer(::grpc::ServerContext* /*context*/, const ::sro::gamebackend::TransferPlayerRequest* /*request*/, ::sro::gamebackend::ConnectGameServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTransferPlayer(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_IsPlaying : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_IsPlaying() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_IsPlaying() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsPlaying(::grpc::ServerContext* /*context*/, const ::sro::character::CharacterTarget* /*request*/, ::sro::gamebackend::ConnectionStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIsPlaying(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ConnectGameServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ConnectGameServer() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ConnectGameServer(context, request, response); }));
    }
    ~WithRawCallbackMethod_ConnectGameServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ConnectGameServer(::grpc::ServerContext* /*context*/, const ::sro::character::CharacterTarget* /*request*/, ::sro::gamebackend::ConnectGameServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ConnectGameServer(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_VerifyConnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_VerifyConnect() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->VerifyConnect(context, request, response); }));
    }
    ~WithRawCallbackMethod_VerifyConnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyConnect(::grpc::ServerContext* /*context*/, const ::sro::gamebackend::VerifyConnectRequest* /*request*/, ::sro::character::CharacterDetails* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VerifyConnect(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_TransferPlayer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_TransferPlayer() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->TransferPlayer(context, request, response); }));
    }
    ~WithRawCallbackMethod_TransferPlayer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TransferPlayer(::grpc::ServerContext* /*context*/, const ::sro::gamebackend::TransferPlayerRequest* /*request*/, ::sro::gamebackend::ConnectGameServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TransferPlayer(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_IsPlaying : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_IsPlaying() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->IsPlaying(context, request, response); }));
    }
    ~WithRawCallbackMethod_IsPlaying() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsPlaying(::grpc::ServerContext* /*context*/, const ::sro::character::CharacterTarget* /*request*/, ::sro::gamebackend::ConnectionStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* IsPlaying(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ConnectGameServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ConnectGameServer() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sro::character::CharacterTarget, ::sro::gamebackend::ConnectGameServerResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sro::character::CharacterTarget, ::sro::gamebackend::ConnectGameServerResponse>* streamer) {
                       return this->StreamedConnectGameServer(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ConnectGameServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ConnectGameServer(::grpc::ServerContext* /*context*/, const ::sro::character::CharacterTarget* /*request*/, ::sro::gamebackend::ConnectGameServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedConnectGameServer(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sro::character::CharacterTarget,::sro::gamebackend::ConnectGameServerResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_VerifyConnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_VerifyConnect() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sro::gamebackend::VerifyConnectRequest, ::sro::character::CharacterDetails>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sro::gamebackend::VerifyConnectRequest, ::sro::character::CharacterDetails>* streamer) {
                       return this->StreamedVerifyConnect(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_VerifyConnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status VerifyConnect(::grpc::ServerContext* /*context*/, const ::sro::gamebackend::VerifyConnectRequest* /*request*/, ::sro::character::CharacterDetails* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedVerifyConnect(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sro::gamebackend::VerifyConnectRequest,::sro::character::CharacterDetails>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_TransferPlayer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_TransferPlayer() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sro::gamebackend::TransferPlayerRequest, ::sro::gamebackend::ConnectGameServerResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sro::gamebackend::TransferPlayerRequest, ::sro::gamebackend::ConnectGameServerResponse>* streamer) {
                       return this->StreamedTransferPlayer(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_TransferPlayer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status TransferPlayer(::grpc::ServerContext* /*context*/, const ::sro::gamebackend::TransferPlayerRequest* /*request*/, ::sro::gamebackend::ConnectGameServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTransferPlayer(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sro::gamebackend::TransferPlayerRequest,::sro::gamebackend::ConnectGameServerResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_IsPlaying : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_IsPlaying() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sro::character::CharacterTarget, ::sro::gamebackend::ConnectionStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sro::character::CharacterTarget, ::sro::gamebackend::ConnectionStatus>* streamer) {
                       return this->StreamedIsPlaying(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_IsPlaying() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status IsPlaying(::grpc::ServerContext* /*context*/, const ::sro::character::CharacterTarget* /*request*/, ::sro::gamebackend::ConnectionStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedIsPlaying(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sro::character::CharacterTarget,::sro::gamebackend::ConnectionStatus>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ConnectGameServer<WithStreamedUnaryMethod_VerifyConnect<WithStreamedUnaryMethod_TransferPlayer<WithStreamedUnaryMethod_IsPlaying<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ConnectGameServer<WithStreamedUnaryMethod_VerifyConnect<WithStreamedUnaryMethod_TransferPlayer<WithStreamedUnaryMethod_IsPlaying<Service > > > > StreamedService;
};

}  // namespace gamebackend
}  // namespace sro


#endif  // GRPC_sro_2fgamebackend_2fconnection_2eproto__INCLUDED
