//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "SGoogleApi/AnnotationsMessage.h"
#include "SSroCharacter/CharacterMessage.h"
#include "SSro/GlobalsMessage.h"
#include "ConnectionMessage.generated.h"

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.ConnectGameServerResponse"))
struct FGrpcSroGamebackendConnectGameServerResponse : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Address = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt32 Port = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString ConnectionId = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.VerifyConnectRequest"))
struct FGrpcSroGamebackendVerifyConnectRequest : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString ConnectionId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString ServerName = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.ConnectionStatus"))
struct FGrpcSroGamebackendConnectionStatus : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Online = false;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.TransferPlayerRequest"))
struct FGrpcSroGamebackendTransferPlayerRequest : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Character = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroLocation Location;
};
