//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SSroGamebackend/ConnectionMessage.h"
#include "ConnectionClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnConnectionServiceConnectGameServerResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGamebackendConnectGameServerResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnConnectionServiceVerifyConnectResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroCharacterCharacterDetails&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnConnectionServiceTransferPlayerResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGamebackendConnectGameServerResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnConnectionServiceIsPlayingResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGamebackendConnectionStatus&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UConnectionServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnConnectionServiceConnectGameServerResponse OnConnectGameServerResponse;

	UPROPERTY(BlueprintAssignable)
	FOnConnectionServiceVerifyConnectResponse OnVerifyConnectResponse;

	UPROPERTY(BlueprintAssignable)
	FOnConnectionServiceTransferPlayerResponse OnTransferPlayerResponse;

	UPROPERTY(BlueprintAssignable)
	FOnConnectionServiceIsPlayingResponse OnIsPlayingResponse;

public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitConnectGameServer();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void ConnectGameServer(FGrpcContextHandle Handle, const FGrpcSroCharacterCharacterTarget& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitVerifyConnect();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void VerifyConnect(FGrpcContextHandle Handle, const FGrpcSroGamebackendVerifyConnectRequest& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitTransferPlayer();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void TransferPlayer(FGrpcContextHandle Handle, const FGrpcSroGamebackendTransferPlayerRequest& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitIsPlaying();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void IsPlaying(FGrpcContextHandle Handle, const FGrpcSroCharacterCharacterTarget& Request, TMap<FString, FString>& MetaData);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void TryCancel(FGrpcContextHandle Handle);
};

