//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "CoreMinimal.h"
#include "Kismet/BlueprintAsyncActionBase.h"
#include "TurboLinkGrpcClient.h"
#include "ConnectionMessage.h"
#include "ConnectionNode.generated.h"

class UConnectionService;
class UConnectionServiceClient;

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallConnectionServiceConnectGameServer : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FConnectionServiceConnectGameServerDelegate, const FGrpcResult&, GrpcResult, const FGrpcSroGamebackendConnectGameServerResponse&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ConnectionService ConnectGameServer"), Category = "TurboLink|ConnectionService")
	static UCallConnectionServiceConnectGameServer* ConnectGameServer(UObject* WorldContextObject, const FGrpcSroCharacterCharacterTarget& Request, TMap<FString, FString>& MetaData);

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceConnectGameServerDelegate OnConnectGameServerResponse;

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceConnectGameServerDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UConnectionService* ConnectionService;
	
	UPROPERTY()
	UConnectionServiceClient* ConnectionServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcSroCharacterCharacterTarget Request;
	EGrpcServiceState ServiceState;
	TMap<FString, FString> MetaData;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroGamebackendConnectGameServerResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallConnectionServiceVerifyConnect : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FConnectionServiceVerifyConnectDelegate, const FGrpcResult&, GrpcResult, const FGrpcSroCharacterCharacterDetails&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ConnectionService VerifyConnect"), Category = "TurboLink|ConnectionService")
	static UCallConnectionServiceVerifyConnect* VerifyConnect(UObject* WorldContextObject, const FGrpcSroGamebackendVerifyConnectRequest& Request, TMap<FString, FString>& MetaData);

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceVerifyConnectDelegate OnVerifyConnectResponse;

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceVerifyConnectDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UConnectionService* ConnectionService;
	
	UPROPERTY()
	UConnectionServiceClient* ConnectionServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcSroGamebackendVerifyConnectRequest Request;
	EGrpcServiceState ServiceState;
	TMap<FString, FString> MetaData;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroCharacterCharacterDetails& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallConnectionServiceTransferPlayer : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FConnectionServiceTransferPlayerDelegate, const FGrpcResult&, GrpcResult, const FGrpcSroGamebackendConnectGameServerResponse&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ConnectionService TransferPlayer"), Category = "TurboLink|ConnectionService")
	static UCallConnectionServiceTransferPlayer* TransferPlayer(UObject* WorldContextObject, const FGrpcSroGamebackendTransferPlayerRequest& Request, TMap<FString, FString>& MetaData);

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceTransferPlayerDelegate OnTransferPlayerResponse;

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceTransferPlayerDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UConnectionService* ConnectionService;
	
	UPROPERTY()
	UConnectionServiceClient* ConnectionServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcSroGamebackendTransferPlayerRequest Request;
	EGrpcServiceState ServiceState;
	TMap<FString, FString> MetaData;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroGamebackendConnectGameServerResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallConnectionServiceIsPlaying : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FConnectionServiceIsPlayingDelegate, const FGrpcResult&, GrpcResult, const FGrpcSroGamebackendConnectionStatus&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ConnectionService IsPlaying"), Category = "TurboLink|ConnectionService")
	static UCallConnectionServiceIsPlaying* IsPlaying(UObject* WorldContextObject, const FGrpcSroCharacterCharacterTarget& Request, TMap<FString, FString>& MetaData);

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceIsPlayingDelegate OnIsPlayingResponse;

	UPROPERTY(BlueprintAssignable)
	FConnectionServiceIsPlayingDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UConnectionService* ConnectionService;
	
	UPROPERTY()
	UConnectionServiceClient* ConnectionServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcSroCharacterCharacterTarget Request;
	EGrpcServiceState ServiceState;
	TMap<FString, FString> MetaData;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroGamebackendConnectionStatus& Response);

	void Shutdown();
};
