//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SSroGamebackend/ServermanagerMessage.h"
#include "ServermanagerClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnServerManagerServiceCreateDimensionResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGamebackendDimension&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnServerManagerServiceDuplicateDimensionResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGamebackendDimension&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnServerManagerServiceGetDimensionResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGamebackendDimension&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnServerManagerServiceGetAllDimensionResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGamebackendDimensions&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnServerManagerServiceEditDimensionResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGamebackendDimension&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnServerManagerServiceDeleteDimensionResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnServerManagerServiceCreateMapResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGamebackendMap&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnServerManagerServiceGetMapResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGamebackendMap&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnServerManagerServiceGetAllMapsResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGamebackendMaps&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnServerManagerServiceEditMapResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroGamebackendMap&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnServerManagerServiceDeleteMapResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UServerManagerServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnServerManagerServiceCreateDimensionResponse OnCreateDimensionResponse;

	UPROPERTY(BlueprintAssignable)
	FOnServerManagerServiceDuplicateDimensionResponse OnDuplicateDimensionResponse;

	UPROPERTY(BlueprintAssignable)
	FOnServerManagerServiceGetDimensionResponse OnGetDimensionResponse;

	UPROPERTY(BlueprintAssignable)
	FOnServerManagerServiceGetAllDimensionResponse OnGetAllDimensionResponse;

	UPROPERTY(BlueprintAssignable)
	FOnServerManagerServiceEditDimensionResponse OnEditDimensionResponse;

	UPROPERTY(BlueprintAssignable)
	FOnServerManagerServiceDeleteDimensionResponse OnDeleteDimensionResponse;

	UPROPERTY(BlueprintAssignable)
	FOnServerManagerServiceCreateMapResponse OnCreateMapResponse;

	UPROPERTY(BlueprintAssignable)
	FOnServerManagerServiceGetMapResponse OnGetMapResponse;

	UPROPERTY(BlueprintAssignable)
	FOnServerManagerServiceGetAllMapsResponse OnGetAllMapsResponse;

	UPROPERTY(BlueprintAssignable)
	FOnServerManagerServiceEditMapResponse OnEditMapResponse;

	UPROPERTY(BlueprintAssignable)
	FOnServerManagerServiceDeleteMapResponse OnDeleteMapResponse;

public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitCreateDimension();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void CreateDimension(FGrpcContextHandle Handle, const FGrpcSroGamebackendCreateDimensionRequest& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitDuplicateDimension();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void DuplicateDimension(FGrpcContextHandle Handle, const FGrpcSroGamebackendDuplicateDimensionRequest& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetDimension();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void GetDimension(FGrpcContextHandle Handle, const FGrpcSroGamebackendDimensionTarget& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetAllDimension();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void GetAllDimension(FGrpcContextHandle Handle, const FGrpcGoogleProtobufEmpty& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitEditDimension();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void EditDimension(FGrpcContextHandle Handle, const FGrpcSroGamebackendEditDimensionRequest& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitDeleteDimension();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void DeleteDimension(FGrpcContextHandle Handle, const FGrpcSroGamebackendDimensionTarget& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitCreateMap();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void CreateMap(FGrpcContextHandle Handle, const FGrpcSroGamebackendCreateMapRequest& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetMap();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void GetMap(FGrpcContextHandle Handle, const FGrpcSroGamebackendMapTarget& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetAllMaps();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void GetAllMaps(FGrpcContextHandle Handle, const FGrpcGoogleProtobufEmpty& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitEditMap();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void EditMap(FGrpcContextHandle Handle, const FGrpcSroGamebackendEditMapRequest& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitDeleteMap();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void DeleteMap(FGrpcContextHandle Handle, const FGrpcSroGamebackendMapTarget& Request, TMap<FString, FString>& MetaData);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void TryCancel(FGrpcContextHandle Handle);
};

