//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "SGoogleApi/AnnotationsMessage.h"
#include "SGoogleProtobuf/EmptyMessage.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "ServermanagerMessage.generated.h"

UENUM(BlueprintType, meta = (DisplayName="SroGamebackend.DimensionTarget.FindBy", ScriptName="EGrpcSroGamebackendDimensionTargetFindBy"))
enum class EGrpcSroGamebackendDimensionTargetFindBy : uint8
{
    Id=0,
    Name=1,
};

UENUM(BlueprintType, meta = (DisplayName="SroGamebackend.MapTarget.FindBy", ScriptName="EGrpcSroGamebackendMapTargetFindBy"))
enum class EGrpcSroGamebackendMapTargetFindBy : uint8
{
    Id=0,
    Name=1,
};

UENUM(BlueprintType, meta = (DisplayName="SroGamebackend.EditDimensionRequest.Optional_name", ScriptName="EGrpcSroGamebackendEditDimensionRequestOptional_name"))
enum class EGrpcSroGamebackendEditDimensionRequestOptional_name : uint8
{
    Name=0,
};

UENUM(BlueprintType, meta = (DisplayName="SroGamebackend.EditDimensionRequest.Optional_version", ScriptName="EGrpcSroGamebackendEditDimensionRequestOptional_version"))
enum class EGrpcSroGamebackendEditDimensionRequestOptional_version : uint8
{
    Version=0,
};

UENUM(BlueprintType, meta = (DisplayName="SroGamebackend.EditDimensionRequest.Optional_location", ScriptName="EGrpcSroGamebackendEditDimensionRequestOptional_location"))
enum class EGrpcSroGamebackendEditDimensionRequestOptional_location : uint8
{
    Location=0,
};

UENUM(BlueprintType, meta = (DisplayName="SroGamebackend.EditMapRequest.Optional_name", ScriptName="EGrpcSroGamebackendEditMapRequestOptional_name"))
enum class EGrpcSroGamebackendEditMapRequestOptional_name : uint8
{
    Name=0,
};

UENUM(BlueprintType, meta = (DisplayName="SroGamebackend.EditMapRequest.Optional_path", ScriptName="EGrpcSroGamebackendEditMapRequestOptional_path"))
enum class EGrpcSroGamebackendEditMapRequestOptional_path : uint8
{
    Path=0,
};

UENUM(BlueprintType, meta = (DisplayName="SroGamebackend.EditMapRequest.Optional_max_players", ScriptName="EGrpcSroGamebackendEditMapRequestOptional_max_players"))
enum class EGrpcSroGamebackendEditMapRequestOptional_max_players : uint8
{
    MaxPlayers=0,
};

UENUM(BlueprintType, meta = (DisplayName="SroGamebackend.EditMapRequest.Optional_instanced", ScriptName="EGrpcSroGamebackendEditMapRequestOptional_instanced"))
enum class EGrpcSroGamebackendEditMapRequestOptional_instanced : uint8
{
    Instanced=0,
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.DimensionTarget.FindBy",
    HasNativeMake = "TurboLinkGrpc.GrpcSroGamebackendDimensionTargetFindByHelperLibrary.MakeFindBy",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroGamebackendDimensionTargetFindByHelperLibrary.BreakFindBy"))
struct FGrpcSroGamebackendDimensionTargetFindBy : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroGamebackendDimensionTargetFindBy FindByCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Id = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.DimensionTarget"))
struct FGrpcSroGamebackendDimensionTarget : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroGamebackendDimensionTargetFindBy FindBy;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.MapTarget.FindBy",
    HasNativeMake = "TurboLinkGrpc.GrpcSroGamebackendMapTargetFindByHelperLibrary.MakeFindBy",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroGamebackendMapTargetFindByHelperLibrary.BreakFindBy"))
struct FGrpcSroGamebackendMapTargetFindBy : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroGamebackendMapTargetFindBy FindByCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Id = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.MapTarget"))
struct FGrpcSroGamebackendMapTarget : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroGamebackendMapTargetFindBy FindBy;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.CreateDimensionRequest"))
struct FGrpcSroGamebackendCreateDimensionRequest : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Version = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FString> MapIds;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Location = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.DuplicateDimensionRequest"))
struct FGrpcSroGamebackendDuplicateDimensionRequest : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroGamebackendDimensionTarget Target;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.EditDimensionRequest.Optional_name",
    HasNativeMake = "TurboLinkGrpc.GrpcSroGamebackendEditDimensionRequestOptional_nameHelperLibrary.MakeOptional_name",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroGamebackendEditDimensionRequestOptional_nameHelperLibrary.BreakOptional_name"))
struct FGrpcSroGamebackendEditDimensionRequestOptional_name : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroGamebackendEditDimensionRequestOptional_name Optional_nameCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.EditDimensionRequest.Optional_version",
    HasNativeMake = "TurboLinkGrpc.GrpcSroGamebackendEditDimensionRequestOptional_versionHelperLibrary.MakeOptional_version",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroGamebackendEditDimensionRequestOptional_versionHelperLibrary.BreakOptional_version"))
struct FGrpcSroGamebackendEditDimensionRequestOptional_version : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroGamebackendEditDimensionRequestOptional_version Optional_versionCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Version = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.EditDimensionRequest.Optional_location",
    HasNativeMake = "TurboLinkGrpc.GrpcSroGamebackendEditDimensionRequestOptional_locationHelperLibrary.MakeOptional_location",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroGamebackendEditDimensionRequestOptional_locationHelperLibrary.BreakOptional_location"))
struct FGrpcSroGamebackendEditDimensionRequestOptional_location : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroGamebackendEditDimensionRequestOptional_location Optional_locationCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Location = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.EditDimensionRequest"))
struct FGrpcSroGamebackendEditDimensionRequest : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroGamebackendDimensionTarget Target;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroGamebackendEditDimensionRequestOptional_name Optional_name;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroGamebackendEditDimensionRequestOptional_version Optional_version;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool EditMaps = false;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FString> MapIds;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroGamebackendEditDimensionRequestOptional_location Optional_location;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.Dimension",
    HasNativeMake = "TurboLinkGrpc.GrpcSroGamebackendDimensionHelperLibrary.MakeDimension",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroGamebackendDimensionHelperLibrary.BreakDimension"))
struct FGrpcSroGamebackendDimension : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Id = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Version = "";

    TArray<TSharedPtr<FGrpcSroGamebackendMap>> Maps;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Location = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.Dimensions"))
struct FGrpcSroGamebackendDimensions : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcSroGamebackendDimension> Dimensions;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.CreateMapRequest"))
struct FGrpcSroGamebackendCreateMapRequest : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Path = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt64 MaxPlayers = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Instanced = false;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.Map"))
struct FGrpcSroGamebackendMap : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Id = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Path = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt64 MaxPlayers = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Instanced = false;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.EditMapRequest.Optional_name",
    HasNativeMake = "TurboLinkGrpc.GrpcSroGamebackendEditMapRequestOptional_nameHelperLibrary.MakeOptional_name",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroGamebackendEditMapRequestOptional_nameHelperLibrary.BreakOptional_name"))
struct FGrpcSroGamebackendEditMapRequestOptional_name : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroGamebackendEditMapRequestOptional_name Optional_nameCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.EditMapRequest.Optional_path",
    HasNativeMake = "TurboLinkGrpc.GrpcSroGamebackendEditMapRequestOptional_pathHelperLibrary.MakeOptional_path",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroGamebackendEditMapRequestOptional_pathHelperLibrary.BreakOptional_path"))
struct FGrpcSroGamebackendEditMapRequestOptional_path : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroGamebackendEditMapRequestOptional_path Optional_pathCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Path = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.EditMapRequest.Optional_max_players",
    HasNativeMake = "TurboLinkGrpc.GrpcSroGamebackendEditMapRequestOptional_max_playersHelperLibrary.MakeOptional_max_players",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroGamebackendEditMapRequestOptional_max_playersHelperLibrary.BreakOptional_max_players"))
struct FGrpcSroGamebackendEditMapRequestOptional_max_players : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroGamebackendEditMapRequestOptional_max_players Optional_max_playersCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt64 MaxPlayers = 0;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.EditMapRequest.Optional_instanced",
    HasNativeMake = "TurboLinkGrpc.GrpcSroGamebackendEditMapRequestOptional_instancedHelperLibrary.MakeOptional_instanced",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroGamebackendEditMapRequestOptional_instancedHelperLibrary.BreakOptional_instanced"))
struct FGrpcSroGamebackendEditMapRequestOptional_instanced : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroGamebackendEditMapRequestOptional_instanced Optional_instancedCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Instanced = false;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.EditMapRequest"))
struct FGrpcSroGamebackendEditMapRequest : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroGamebackendMapTarget Target;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroGamebackendEditMapRequestOptional_name Optional_name;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroGamebackendEditMapRequestOptional_path Optional_path;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroGamebackendEditMapRequestOptional_max_players Optional_max_players;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroGamebackendEditMapRequestOptional_instanced Optional_instanced;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroGamebackend.Maps"))
struct FGrpcSroGamebackendMaps : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcSroGamebackendMap> Maps;
};

UCLASS()
class UGrpcSroGamebackendDimensionTargetFindByHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static FGrpcSroGamebackendDimensionTargetFindBy MakeFindBy(EGrpcSroGamebackendDimensionTargetFindBy FindByCase, 
        FString Id, FString Name 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static void BreakFindBy(const FGrpcSroGamebackendDimensionTargetFindBy& FindBy, EGrpcSroGamebackendDimensionTargetFindBy& FindByCase, 
        FString& Id, FString& Name 
    );
};

UCLASS()
class UGrpcSroGamebackendMapTargetFindByHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static FGrpcSroGamebackendMapTargetFindBy MakeFindBy(EGrpcSroGamebackendMapTargetFindBy FindByCase, 
        FString Id, FString Name 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static void BreakFindBy(const FGrpcSroGamebackendMapTargetFindBy& FindBy, EGrpcSroGamebackendMapTargetFindBy& FindByCase, 
        FString& Id, FString& Name 
    );
};

UCLASS()
class UGrpcSroGamebackendEditDimensionRequestOptional_nameHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static FGrpcSroGamebackendEditDimensionRequestOptional_name MakeOptional_name(EGrpcSroGamebackendEditDimensionRequestOptional_name Optional_nameCase, 
        FString Name 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static void BreakOptional_name(const FGrpcSroGamebackendEditDimensionRequestOptional_name& Optional_name, EGrpcSroGamebackendEditDimensionRequestOptional_name& Optional_nameCase, 
        FString& Name 
    );
};

UCLASS()
class UGrpcSroGamebackendEditDimensionRequestOptional_versionHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static FGrpcSroGamebackendEditDimensionRequestOptional_version MakeOptional_version(EGrpcSroGamebackendEditDimensionRequestOptional_version Optional_versionCase, 
        FString Version 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static void BreakOptional_version(const FGrpcSroGamebackendEditDimensionRequestOptional_version& Optional_version, EGrpcSroGamebackendEditDimensionRequestOptional_version& Optional_versionCase, 
        FString& Version 
    );
};

UCLASS()
class UGrpcSroGamebackendEditDimensionRequestOptional_locationHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static FGrpcSroGamebackendEditDimensionRequestOptional_location MakeOptional_location(EGrpcSroGamebackendEditDimensionRequestOptional_location Optional_locationCase, 
        FString Location 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static void BreakOptional_location(const FGrpcSroGamebackendEditDimensionRequestOptional_location& Optional_location, EGrpcSroGamebackendEditDimensionRequestOptional_location& Optional_locationCase, 
        FString& Location 
    );
};

UCLASS()
class UGrpcSroGamebackendDimensionHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static FGrpcSroGamebackendDimension MakeDimension( 
        FString Id, FString Name, FString Version, 
        TArray<FGrpcSroGamebackendMap> Maps, FString Location 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static void BreakDimension(const FGrpcSroGamebackendDimension& Dimension,  
        FString& Id, FString& Name, FString& Version, 
        TArray<FGrpcSroGamebackendMap>& Maps, FString& Location 
    );
};

UCLASS()
class UGrpcSroGamebackendEditMapRequestOptional_nameHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static FGrpcSroGamebackendEditMapRequestOptional_name MakeOptional_name(EGrpcSroGamebackendEditMapRequestOptional_name Optional_nameCase, 
        FString Name 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static void BreakOptional_name(const FGrpcSroGamebackendEditMapRequestOptional_name& Optional_name, EGrpcSroGamebackendEditMapRequestOptional_name& Optional_nameCase, 
        FString& Name 
    );
};

UCLASS()
class UGrpcSroGamebackendEditMapRequestOptional_pathHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static FGrpcSroGamebackendEditMapRequestOptional_path MakeOptional_path(EGrpcSroGamebackendEditMapRequestOptional_path Optional_pathCase, 
        FString Path 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static void BreakOptional_path(const FGrpcSroGamebackendEditMapRequestOptional_path& Optional_path, EGrpcSroGamebackendEditMapRequestOptional_path& Optional_pathCase, 
        FString& Path 
    );
};

UCLASS()
class UGrpcSroGamebackendEditMapRequestOptional_max_playersHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static FGrpcSroGamebackendEditMapRequestOptional_max_players MakeOptional_max_players(EGrpcSroGamebackendEditMapRequestOptional_max_players Optional_max_playersCase, 
        FUInt64 MaxPlayers 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static void BreakOptional_max_players(const FGrpcSroGamebackendEditMapRequestOptional_max_players& Optional_max_players, EGrpcSroGamebackendEditMapRequestOptional_max_players& Optional_max_playersCase, 
        FUInt64& MaxPlayers 
    );
};

UCLASS()
class UGrpcSroGamebackendEditMapRequestOptional_instancedHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static FGrpcSroGamebackendEditMapRequestOptional_instanced MakeOptional_instanced(EGrpcSroGamebackendEditMapRequestOptional_instanced Optional_instancedCase, 
        bool Instanced 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroGamebackend", meta=(BlueprintThreadSafe))
    static void BreakOptional_instanced(const FGrpcSroGamebackendEditMapRequestOptional_instanced& Optional_instanced, EGrpcSroGamebackendEditMapRequestOptional_instanced& Optional_instancedCase, 
        bool& Instanced 
    );
};
