//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "GlobalsMessage.generated.h"

UENUM(BlueprintType, meta = (DisplayName="Sro.UserTarget.Target", ScriptName="EGrpcSroUserTargetTarget"))
enum class EGrpcSroUserTargetTarget : uint8
{
    Id=0,
    Username=1,
};

USTRUCT(BlueprintType, meta = (DisplayName="Sro.UserTarget.Target",
    HasNativeMake = "TurboLinkGrpc.GrpcSroUserTargetTargetHelperLibrary.MakeTarget",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroUserTargetTargetHelperLibrary.BreakTarget"))
struct FGrpcSroUserTargetTarget : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroUserTargetTarget TargetCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Id = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Username = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Sro.UserTarget"))
struct FGrpcSroUserTarget : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroUserTargetTarget Target;
};

USTRUCT(BlueprintType, meta = (DisplayName="Sro.Location"))
struct FGrpcSroLocation : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString World = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float X = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float Y = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float Z = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float Roll = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float Pitch = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float Yaw = 0;
};

UCLASS()
class UGrpcSroUserTargetTargetHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Sro", meta=(BlueprintThreadSafe))
    static FGrpcSroUserTargetTarget MakeTarget(EGrpcSroUserTargetTarget TargetCase, 
        FString Id, FString Username 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Sro", meta=(BlueprintThreadSafe))
    static void BreakTarget(const FGrpcSroUserTargetTarget& Target, EGrpcSroUserTargetTarget& TargetCase, 
        FString& Id, FString& Username 
    );
};
