//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "SSro/GlobalsMessage.h"
#include "TurboLinkGrpcContext.h"
#include "sro/globals.pb.h"

void GRPC_TO_TURBOLINK(const ::sro::UserTarget* in, FGrpcSroUserTarget* out);
void TURBOLINK_TO_GRPC(const FGrpcSroUserTarget* in, ::sro::UserTarget* out);

void GRPC_TO_TURBOLINK(const ::sro::Location* in, FGrpcSroLocation* out);
void TURBOLINK_TO_GRPC(const FGrpcSroLocation* in, ::sro::Location* out);

