//Generated by TurboLink CodeGenerator, do not edit!
#include "GlobalsMarshaling.h"

void GRPC_TO_TURBOLINK(const ::sro::UserTarget* in, FGrpcSroUserTarget* out)
{
    switch(in->target_case())
    {
    case ::sro::UserTarget::kId:
        out->Target.Id=UTF8_TO_TCHAR(in->id().c_str());
        out->Target.TargetCase = EGrpcSroUserTargetTarget::Id;
        break;
    case ::sro::UserTarget::kUsername:
        out->Target.Username=UTF8_TO_TCHAR(in->username().c_str());
        out->Target.TargetCase = EGrpcSroUserTargetTarget::Username;
        break;
    }
}

void TURBOLINK_TO_GRPC(const FGrpcSroUserTarget* in, ::sro::UserTarget* out)
{
    switch (in->Target.TargetCase)
    {
    case EGrpcSroUserTargetTarget::Id:
        out->set_id(TCHAR_TO_UTF8(*(in->Target.Id)));
        break;
    case EGrpcSroUserTargetTarget::Username:
        out->set_username(TCHAR_TO_UTF8(*(in->Target.Username)));
        break;
    }
}

void GRPC_TO_TURBOLINK(const ::sro::Location* in, FGrpcSroLocation* out)
{
    out->World=UTF8_TO_TCHAR(in->world().c_str());
    out->X=in->x();
    out->Y=in->y();
    out->Z=in->z();
    out->Roll=in->roll();
    out->Pitch=in->pitch();
    out->Yaw=in->yaw();
}

void TURBOLINK_TO_GRPC(const FGrpcSroLocation* in, ::sro::Location* out)
{
    out->set_world(TCHAR_TO_UTF8(*(in->World)));
    out->set_x(in->X);
    out->set_y(in->Y);
    out->set_z(in->Z);
    out->set_roll(in->Roll);
    out->set_pitch(in->Pitch);
    out->set_yaw(in->Yaw);
}

