//Generated by TurboLink CodeGenerator, do not edit!
#include "SSroChat/ChatService.h"
#include "SSroChat/ChatClient.h"
#include "ChatService_Private.h"
#include "ChatMarshaling.h"
#include "SGoogleApi/AnnotationsMarshaling.h"
#include "SGoogleProtobuf/EmptyMarshaling.h"
#include "SSroCharacter/CharacterMarshaling.h"
#include "TurboLinkGrpcManager_Private.h"
#include "TurboLinkGrpcUtilities.h"

UChatService::UChatService()
	: d(new UChatService::Private())
{
}

UChatService::~UChatService()
{
	delete d;
}

void UChatService::Connect()
{
	FString serviceEndPoint = UTurboLinkGrpcUtilities::GetTurboLinkGrpcConfig()->GetServiceEndPoint(TEXT("ChatService"));
	UE_LOG(LogTurboLink, Warning, TEXT("Connect to ChatService: '%s'"), *serviceEndPoint);

	if (d->Channel == nullptr) {
		d->Channel = TurboLinkManager->d->CreateServiceChannel(TCHAR_TO_UTF8(*serviceEndPoint), this);
	}
	if (d->Stub == nullptr) {
		d->Stub = sro::chat::ChatService::NewStub(d->Channel->RpcChannel);
	}

	grpc_connectivity_state currentChannelState = d->Channel->RpcChannel->GetState(true);
	if (OnServiceStateChanged.IsBound())
	{
		OnServiceStateChanged.Broadcast(UTurboLinkGrpcManager::Private::GrpcStateToServiceState(currentChannelState));
	}
}

EGrpcServiceState UChatService::GetServiceState() const
{
	if (d->Channel == nullptr) return EGrpcServiceState::NotCreate;

	auto rpcChannelState = d->Channel->RpcChannel->GetState(false);
	return UTurboLinkGrpcManager::Private::GrpcStateToServiceState(rpcChannelState);
}

UChatServiceClient* UChatService::MakeClient()
{
	auto client = UGrpcService::MakeClient<UChatServiceClient>();
	return client;
}

void UChatService::Shutdown()
{
	Super::Shutdown();
	d->Stub = nullptr;
	if (d->Channel != nullptr) {
		TurboLinkManager->d->RemoveServiceChannel(d->Channel, this);
		d->Channel = nullptr;
	}
}

void UChatService::CallConnectChannel(const FGrpcSroChatChatChannelTarget& Request, FConnectChannelResponseLambda ResponseLambda, FConnectChannelFinishLambda FinishLambda, TMap<FString, FString>& MetaData)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UChatServiceConnectChannelLambdaWrapper* lambdaWrapper = NewObject<UChatServiceConnectChannelLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->FinishLambda = FinishLambda;
	lambdaWrapper->Handle = InnerClient->InitConnectChannel();
	InnerClient->OnConnectChannelResponse.AddUniqueDynamic(lambdaWrapper, &UChatServiceConnectChannelLambdaWrapper::OnResponse);
	InnerClient->OnContextStateChange.AddUniqueDynamic(lambdaWrapper, &UChatServiceConnectChannelLambdaWrapper::OnContextStateChanged);
	InnerClient->ConnectChannel(lambdaWrapper->Handle, Request, MetaData);
}

void UChatService::CallConnectDirectMessage(const FGrpcSroCharacterCharacterTarget& Request, FConnectDirectMessageResponseLambda ResponseLambda, FConnectDirectMessageFinishLambda FinishLambda, TMap<FString, FString>& MetaData)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UChatServiceConnectDirectMessageLambdaWrapper* lambdaWrapper = NewObject<UChatServiceConnectDirectMessageLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->FinishLambda = FinishLambda;
	lambdaWrapper->Handle = InnerClient->InitConnectDirectMessage();
	InnerClient->OnConnectDirectMessageResponse.AddUniqueDynamic(lambdaWrapper, &UChatServiceConnectDirectMessageLambdaWrapper::OnResponse);
	InnerClient->OnContextStateChange.AddUniqueDynamic(lambdaWrapper, &UChatServiceConnectDirectMessageLambdaWrapper::OnContextStateChanged);
	InnerClient->ConnectDirectMessage(lambdaWrapper->Handle, Request, MetaData);
}

void UChatService::CallSendChatMessage(const FGrpcSroChatSendChatMessageRequest& Request, FSendChatMessageResponseLambda ResponseLambda, TMap<FString, FString>& MetaData)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UChatServiceSendChatMessageLambdaWrapper* lambdaWrapper = NewObject<UChatServiceSendChatMessageLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitSendChatMessage();
	InnerClient->OnSendChatMessageResponse.AddUniqueDynamic(lambdaWrapper, &UChatServiceSendChatMessageLambdaWrapper::OnResponse);
	InnerClient->SendChatMessage(lambdaWrapper->Handle, Request, MetaData);
}

void UChatService::CallSendDirectMessage(const FGrpcSroChatSendDirectMessageRequest& Request, FSendDirectMessageResponseLambda ResponseLambda, TMap<FString, FString>& MetaData)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UChatServiceSendDirectMessageLambdaWrapper* lambdaWrapper = NewObject<UChatServiceSendDirectMessageLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitSendDirectMessage();
	InnerClient->OnSendDirectMessageResponse.AddUniqueDynamic(lambdaWrapper, &UChatServiceSendDirectMessageLambdaWrapper::OnResponse);
	InnerClient->SendDirectMessage(lambdaWrapper->Handle, Request, MetaData);
}

void UChatService::CallGetChannel(const FGrpcSroChatChatChannelTarget& Request, FGetChannelResponseLambda ResponseLambda, TMap<FString, FString>& MetaData)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UChatServiceGetChannelLambdaWrapper* lambdaWrapper = NewObject<UChatServiceGetChannelLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitGetChannel();
	InnerClient->OnGetChannelResponse.AddUniqueDynamic(lambdaWrapper, &UChatServiceGetChannelLambdaWrapper::OnResponse);
	InnerClient->GetChannel(lambdaWrapper->Handle, Request, MetaData);
}

void UChatService::CallAllChatChannels(const FGrpcGoogleProtobufEmpty& Request, FAllChatChannelsResponseLambda ResponseLambda, TMap<FString, FString>& MetaData)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UChatServiceAllChatChannelsLambdaWrapper* lambdaWrapper = NewObject<UChatServiceAllChatChannelsLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitAllChatChannels();
	InnerClient->OnAllChatChannelsResponse.AddUniqueDynamic(lambdaWrapper, &UChatServiceAllChatChannelsLambdaWrapper::OnResponse);
	InnerClient->AllChatChannels(lambdaWrapper->Handle, Request, MetaData);
}

void UChatService::CallCreateChannel(const FGrpcSroChatCreateChannelMessage& Request, FCreateChannelResponseLambda ResponseLambda, TMap<FString, FString>& MetaData)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UChatServiceCreateChannelLambdaWrapper* lambdaWrapper = NewObject<UChatServiceCreateChannelLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitCreateChannel();
	InnerClient->OnCreateChannelResponse.AddUniqueDynamic(lambdaWrapper, &UChatServiceCreateChannelLambdaWrapper::OnResponse);
	InnerClient->CreateChannel(lambdaWrapper->Handle, Request, MetaData);
}

void UChatService::CallDeleteChannel(const FGrpcSroChatChatChannelTarget& Request, FDeleteChannelResponseLambda ResponseLambda, TMap<FString, FString>& MetaData)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UChatServiceDeleteChannelLambdaWrapper* lambdaWrapper = NewObject<UChatServiceDeleteChannelLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitDeleteChannel();
	InnerClient->OnDeleteChannelResponse.AddUniqueDynamic(lambdaWrapper, &UChatServiceDeleteChannelLambdaWrapper::OnResponse);
	InnerClient->DeleteChannel(lambdaWrapper->Handle, Request, MetaData);
}

void UChatService::CallEditChannel(const FGrpcSroChatUpdateChatChannelRequest& Request, FEditChannelResponseLambda ResponseLambda, TMap<FString, FString>& MetaData)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UChatServiceEditChannelLambdaWrapper* lambdaWrapper = NewObject<UChatServiceEditChannelLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitEditChannel();
	InnerClient->OnEditChannelResponse.AddUniqueDynamic(lambdaWrapper, &UChatServiceEditChannelLambdaWrapper::OnResponse);
	InnerClient->EditChannel(lambdaWrapper->Handle, Request, MetaData);
}

void UChatService::CallGetAuthorizedChatChannels(const FGrpcSroCharacterCharacterTarget& Request, FGetAuthorizedChatChannelsResponseLambda ResponseLambda, TMap<FString, FString>& MetaData)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UChatServiceGetAuthorizedChatChannelsLambdaWrapper* lambdaWrapper = NewObject<UChatServiceGetAuthorizedChatChannelsLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitGetAuthorizedChatChannels();
	InnerClient->OnGetAuthorizedChatChannelsResponse.AddUniqueDynamic(lambdaWrapper, &UChatServiceGetAuthorizedChatChannelsLambdaWrapper::OnResponse);
	InnerClient->GetAuthorizedChatChannels(lambdaWrapper->Handle, Request, MetaData);
}

void UChatService::CallUpdateUserChatChannelAuthorizations(const FGrpcSroChatRequestChatChannelAuthChange& Request, FUpdateUserChatChannelAuthorizationsResponseLambda ResponseLambda, TMap<FString, FString>& MetaData)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UChatServiceUpdateUserChatChannelAuthorizationsLambdaWrapper* lambdaWrapper = NewObject<UChatServiceUpdateUserChatChannelAuthorizationsLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitUpdateUserChatChannelAuthorizations();
	InnerClient->OnUpdateUserChatChannelAuthorizationsResponse.AddUniqueDynamic(lambdaWrapper, &UChatServiceUpdateUserChatChannelAuthorizationsLambdaWrapper::OnResponse);
	InnerClient->UpdateUserChatChannelAuthorizations(lambdaWrapper->Handle, Request, MetaData);
}

void UChatService::CallSetUserChatChannelAuthorizations(const FGrpcSroChatRequestSetChannelAuth& Request, FSetUserChatChannelAuthorizationsResponseLambda ResponseLambda, TMap<FString, FString>& MetaData)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UChatServiceSetUserChatChannelAuthorizationsLambdaWrapper* lambdaWrapper = NewObject<UChatServiceSetUserChatChannelAuthorizationsLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitSetUserChatChannelAuthorizations();
	InnerClient->OnSetUserChatChannelAuthorizationsResponse.AddUniqueDynamic(lambdaWrapper, &UChatServiceSetUserChatChannelAuthorizationsLambdaWrapper::OnResponse);
	InnerClient->SetUserChatChannelAuthorizations(lambdaWrapper->Handle, Request, MetaData);
}
