//Generated by TurboLink CodeGenerator, do not edit!
#include "SSroChat/ChatMessage.h"

FGrpcSroChatUpdateChatChannelRequestOptional_name UGrpcSroChatUpdateChatChannelRequestOptional_nameHelperLibrary::MakeOptional_name(EGrpcSroChatUpdateChatChannelRequestOptional_name Optional_nameCase, 
    FString Name 
)
{
    FGrpcSroChatUpdateChatChannelRequestOptional_name Optional_name;
    Optional_name.Optional_nameCase = Optional_nameCase;
    Optional_name.Name = Name;

    return Optional_name;
}

void UGrpcSroChatUpdateChatChannelRequestOptional_nameHelperLibrary::BreakOptional_name(const FGrpcSroChatUpdateChatChannelRequestOptional_name& Optional_name, EGrpcSroChatUpdateChatChannelRequestOptional_name& Optional_nameCase, 
    FString& Name 
)
{
    Optional_nameCase = Optional_name.Optional_nameCase;
    Name = Optional_name.Name;
}

FGrpcSroChatUpdateChatChannelRequestOptional_dimension UGrpcSroChatUpdateChatChannelRequestOptional_dimensionHelperLibrary::MakeOptional_dimension(EGrpcSroChatUpdateChatChannelRequestOptional_dimension Optional_dimensionCase, 
    FString Dimension 
)
{
    FGrpcSroChatUpdateChatChannelRequestOptional_dimension Optional_dimension;
    Optional_dimension.Optional_dimensionCase = Optional_dimensionCase;
    Optional_dimension.Dimension = Dimension;

    return Optional_dimension;
}

void UGrpcSroChatUpdateChatChannelRequestOptional_dimensionHelperLibrary::BreakOptional_dimension(const FGrpcSroChatUpdateChatChannelRequestOptional_dimension& Optional_dimension, EGrpcSroChatUpdateChatChannelRequestOptional_dimension& Optional_dimensionCase, 
    FString& Dimension 
)
{
    Optional_dimensionCase = Optional_dimension.Optional_dimensionCase;
    Dimension = Optional_dimension.Dimension;
}

