//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SSroCharacter/CharacterMessage.h"
#include "CharacterClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnCharacterServiceGetCharactersResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroCharacterCharactersDetails&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnCharacterServiceGetCharacterResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroCharacterCharacterDetails&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnCharacterServiceCreateCharacterResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroCharacterCharacterDetails&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnCharacterServiceDeleteCharacterResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnCharacterServiceGetAllCharactersForUserResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroCharacterCharactersDetails&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnCharacterServiceEditCharacterResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnCharacterServiceAddCharacterPlayTimeResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroCharacterPlayTimeResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnCharacterServiceGetInventoryResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroCharacterInventory&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnCharacterServiceSetInventoryResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UCharacterServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnCharacterServiceGetCharactersResponse OnGetCharactersResponse;

	UPROPERTY(BlueprintAssignable)
	FOnCharacterServiceGetCharacterResponse OnGetCharacterResponse;

	UPROPERTY(BlueprintAssignable)
	FOnCharacterServiceCreateCharacterResponse OnCreateCharacterResponse;

	UPROPERTY(BlueprintAssignable)
	FOnCharacterServiceDeleteCharacterResponse OnDeleteCharacterResponse;

	UPROPERTY(BlueprintAssignable)
	FOnCharacterServiceGetAllCharactersForUserResponse OnGetAllCharactersForUserResponse;

	UPROPERTY(BlueprintAssignable)
	FOnCharacterServiceEditCharacterResponse OnEditCharacterResponse;

	UPROPERTY(BlueprintAssignable)
	FOnCharacterServiceAddCharacterPlayTimeResponse OnAddCharacterPlayTimeResponse;

	UPROPERTY(BlueprintAssignable)
	FOnCharacterServiceGetInventoryResponse OnGetInventoryResponse;

	UPROPERTY(BlueprintAssignable)
	FOnCharacterServiceSetInventoryResponse OnSetInventoryResponse;

public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetCharacters();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void GetCharacters(FGrpcContextHandle Handle, const FGrpcGoogleProtobufEmpty& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetCharacter();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void GetCharacter(FGrpcContextHandle Handle, const FGrpcSroCharacterCharacterTarget& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitCreateCharacter();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void CreateCharacter(FGrpcContextHandle Handle, const FGrpcSroCharacterCreateCharacterRequest& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitDeleteCharacter();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void DeleteCharacter(FGrpcContextHandle Handle, const FGrpcSroCharacterCharacterTarget& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetAllCharactersForUser();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void GetAllCharactersForUser(FGrpcContextHandle Handle, const FGrpcSroUserTarget& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitEditCharacter();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void EditCharacter(FGrpcContextHandle Handle, const FGrpcSroCharacterEditCharacterRequest& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitAddCharacterPlayTime();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void AddCharacterPlayTime(FGrpcContextHandle Handle, const FGrpcSroCharacterAddPlayTimeRequest& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetInventory();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void GetInventory(FGrpcContextHandle Handle, const FGrpcSroCharacterCharacterTarget& Request, TMap<FString, FString>& MetaData);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitSetInventory();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void SetInventory(FGrpcContextHandle Handle, const FGrpcSroCharacterUpdateInventoryRequest& Request, TMap<FString, FString>& MetaData);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void TryCancel(FGrpcContextHandle Handle);
};

