//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "SGoogleApi/AnnotationsMessage.h"
#include "SGoogleProtobuf/EmptyMessage.h"
#include "SSro/GlobalsMessage.h"
#include "SSroGamebackend/ServermanagerMessage.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "CharacterMessage.generated.h"

UENUM(BlueprintType, meta = (DisplayName="SroCharacter.CharacterTarget.Type", ScriptName="EGrpcSroCharacterCharacterTargetType"))
enum class EGrpcSroCharacterCharacterTargetType : uint8
{
    Id=0,
    Name=1,
};

UENUM(BlueprintType, meta = (DisplayName="SroCharacter.EditCharacterRequest.Optional_owner_id", ScriptName="EGrpcSroCharacterEditCharacterRequestOptional_owner_id"))
enum class EGrpcSroCharacterEditCharacterRequestOptional_owner_id : uint8
{
    OwnerId=0,
};

UENUM(BlueprintType, meta = (DisplayName="SroCharacter.EditCharacterRequest.Optional_new_name", ScriptName="EGrpcSroCharacterEditCharacterRequestOptional_new_name"))
enum class EGrpcSroCharacterEditCharacterRequestOptional_new_name : uint8
{
    NewName=0,
};

UENUM(BlueprintType, meta = (DisplayName="SroCharacter.EditCharacterRequest.Optional_gender", ScriptName="EGrpcSroCharacterEditCharacterRequestOptional_gender"))
enum class EGrpcSroCharacterEditCharacterRequestOptional_gender : uint8
{
    Gender=0,
};

UENUM(BlueprintType, meta = (DisplayName="SroCharacter.EditCharacterRequest.Optional_realm", ScriptName="EGrpcSroCharacterEditCharacterRequestOptional_realm"))
enum class EGrpcSroCharacterEditCharacterRequestOptional_realm : uint8
{
    Realm=0,
};

UENUM(BlueprintType, meta = (DisplayName="SroCharacter.EditCharacterRequest.Optional_play_time", ScriptName="EGrpcSroCharacterEditCharacterRequestOptional_play_time"))
enum class EGrpcSroCharacterEditCharacterRequestOptional_play_time : uint8
{
    PlayTime=0,
};

UENUM(BlueprintType, meta = (DisplayName="SroCharacter.EditCharacterRequest.Optional_location", ScriptName="EGrpcSroCharacterEditCharacterRequestOptional_location"))
enum class EGrpcSroCharacterEditCharacterRequestOptional_location : uint8
{
    Location=0,
};

UENUM(BlueprintType, meta = (DisplayName="SroCharacter.EditCharacterRequest.Optional_dimension", ScriptName="EGrpcSroCharacterEditCharacterRequestOptional_dimension"))
enum class EGrpcSroCharacterEditCharacterRequestOptional_dimension : uint8
{
    Dimension=0,
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.PlayTimeResponse"))
struct FGrpcSroCharacterPlayTimeResponse : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt64 Time = 0;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.AddPlayTimeRequest",
    HasNativeMake = "TurboLinkGrpc.GrpcSroCharacterAddPlayTimeRequestHelperLibrary.MakeAddPlayTimeRequest",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroCharacterAddPlayTimeRequestHelperLibrary.BreakAddPlayTimeRequest"))
struct FGrpcSroCharacterAddPlayTimeRequest : public FGrpcMessage
{
    GENERATED_BODY()

    TSharedPtr<FGrpcSroCharacterCharacterTarget> Character;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt64 Time = 0;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.CreateCharacterRequest"))
struct FGrpcSroCharacterCreateCharacterRequest : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroUserTarget Owner;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Gender = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Realm = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroGamebackendDimensionTarget Dimension;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.CharacterTarget.Type",
    HasNativeMake = "TurboLinkGrpc.GrpcSroCharacterCharacterTargetTypeHelperLibrary.MakeType",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroCharacterCharacterTargetTypeHelperLibrary.BreakType"))
struct FGrpcSroCharacterCharacterTargetType : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroCharacterCharacterTargetType TypeCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt64 Id = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.CharacterTarget"))
struct FGrpcSroCharacterCharacterTarget : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroCharacterCharacterTargetType Type;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.EditCharacterRequest.Optional_owner_id",
    HasNativeMake = "TurboLinkGrpc.GrpcSroCharacterEditCharacterRequestOptional_owner_idHelperLibrary.MakeOptional_owner_id",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroCharacterEditCharacterRequestOptional_owner_idHelperLibrary.BreakOptional_owner_id"))
struct FGrpcSroCharacterEditCharacterRequestOptional_owner_id : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroCharacterEditCharacterRequestOptional_owner_id Optional_owner_idCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString OwnerId = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.EditCharacterRequest.Optional_new_name",
    HasNativeMake = "TurboLinkGrpc.GrpcSroCharacterEditCharacterRequestOptional_new_nameHelperLibrary.MakeOptional_new_name",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroCharacterEditCharacterRequestOptional_new_nameHelperLibrary.BreakOptional_new_name"))
struct FGrpcSroCharacterEditCharacterRequestOptional_new_name : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroCharacterEditCharacterRequestOptional_new_name Optional_new_nameCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString NewName = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.EditCharacterRequest.Optional_gender",
    HasNativeMake = "TurboLinkGrpc.GrpcSroCharacterEditCharacterRequestOptional_genderHelperLibrary.MakeOptional_gender",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroCharacterEditCharacterRequestOptional_genderHelperLibrary.BreakOptional_gender"))
struct FGrpcSroCharacterEditCharacterRequestOptional_gender : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroCharacterEditCharacterRequestOptional_gender Optional_genderCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Gender = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.EditCharacterRequest.Optional_realm",
    HasNativeMake = "TurboLinkGrpc.GrpcSroCharacterEditCharacterRequestOptional_realmHelperLibrary.MakeOptional_realm",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroCharacterEditCharacterRequestOptional_realmHelperLibrary.BreakOptional_realm"))
struct FGrpcSroCharacterEditCharacterRequestOptional_realm : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroCharacterEditCharacterRequestOptional_realm Optional_realmCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Realm = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.EditCharacterRequest.Optional_play_time",
    HasNativeMake = "TurboLinkGrpc.GrpcSroCharacterEditCharacterRequestOptional_play_timeHelperLibrary.MakeOptional_play_time",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroCharacterEditCharacterRequestOptional_play_timeHelperLibrary.BreakOptional_play_time"))
struct FGrpcSroCharacterEditCharacterRequestOptional_play_time : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroCharacterEditCharacterRequestOptional_play_time Optional_play_timeCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt64 PlayTime = 0;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.EditCharacterRequest.Optional_location",
    HasNativeMake = "TurboLinkGrpc.GrpcSroCharacterEditCharacterRequestOptional_locationHelperLibrary.MakeOptional_location",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroCharacterEditCharacterRequestOptional_locationHelperLibrary.BreakOptional_location"))
struct FGrpcSroCharacterEditCharacterRequestOptional_location : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroCharacterEditCharacterRequestOptional_location Optional_locationCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroLocation Location;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.EditCharacterRequest.Optional_dimension",
    HasNativeMake = "TurboLinkGrpc.GrpcSroCharacterEditCharacterRequestOptional_dimensionHelperLibrary.MakeOptional_dimension",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroCharacterEditCharacterRequestOptional_dimensionHelperLibrary.BreakOptional_dimension"))
struct FGrpcSroCharacterEditCharacterRequestOptional_dimension : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroCharacterEditCharacterRequestOptional_dimension Optional_dimensionCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroGamebackendDimensionTarget Dimension;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.EditCharacterRequest"))
struct FGrpcSroCharacterEditCharacterRequest : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroCharacterCharacterTarget Target;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroCharacterEditCharacterRequestOptional_owner_id Optional_owner_id;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroCharacterEditCharacterRequestOptional_new_name Optional_new_name;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroCharacterEditCharacterRequestOptional_gender Optional_gender;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroCharacterEditCharacterRequestOptional_realm Optional_realm;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroCharacterEditCharacterRequestOptional_play_time Optional_play_time;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroCharacterEditCharacterRequestOptional_location Optional_location;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroCharacterEditCharacterRequestOptional_dimension Optional_dimension;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.CharacterDetails"))
struct FGrpcSroCharacterCharacterDetails : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt64 Id = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Owner = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Gender = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Realm = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt64 PlayTime = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroLocation Location;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Dimension = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.CharactersDetails"))
struct FGrpcSroCharacterCharactersDetails : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcSroCharacterCharacterDetails> Characters;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.InventoryItem"))
struct FGrpcSroCharacterInventoryItem : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Id = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt32 Slot = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt64 Quantity = 0;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.Inventory"))
struct FGrpcSroCharacterInventory : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcSroCharacterInventoryItem> InventoryItems;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcSroCharacterInventoryItem> BankItems;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroCharacter.UpdateInventoryRequest"))
struct FGrpcSroCharacterUpdateInventoryRequest : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroCharacterCharacterTarget Target;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcSroCharacterInventoryItem> InventoryItems;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcSroCharacterInventoryItem> BankItems;
};

UCLASS()
class UGrpcSroCharacterAddPlayTimeRequestHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static FGrpcSroCharacterAddPlayTimeRequest MakeAddPlayTimeRequest( 
        FGrpcSroCharacterCharacterTarget Character, FUInt64 Time 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static void BreakAddPlayTimeRequest(const FGrpcSroCharacterAddPlayTimeRequest& AddPlayTimeRequest,  
        FGrpcSroCharacterCharacterTarget& Character, FUInt64& Time 
    );
};

UCLASS()
class UGrpcSroCharacterCharacterTargetTypeHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static FGrpcSroCharacterCharacterTargetType MakeType(EGrpcSroCharacterCharacterTargetType TypeCase, 
        FUInt64 Id, FString Name 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static void BreakType(const FGrpcSroCharacterCharacterTargetType& Type, EGrpcSroCharacterCharacterTargetType& TypeCase, 
        FUInt64& Id, FString& Name 
    );
};

UCLASS()
class UGrpcSroCharacterEditCharacterRequestOptional_owner_idHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static FGrpcSroCharacterEditCharacterRequestOptional_owner_id MakeOptional_owner_id(EGrpcSroCharacterEditCharacterRequestOptional_owner_id Optional_owner_idCase, 
        FString OwnerId 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static void BreakOptional_owner_id(const FGrpcSroCharacterEditCharacterRequestOptional_owner_id& Optional_owner_id, EGrpcSroCharacterEditCharacterRequestOptional_owner_id& Optional_owner_idCase, 
        FString& OwnerId 
    );
};

UCLASS()
class UGrpcSroCharacterEditCharacterRequestOptional_new_nameHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static FGrpcSroCharacterEditCharacterRequestOptional_new_name MakeOptional_new_name(EGrpcSroCharacterEditCharacterRequestOptional_new_name Optional_new_nameCase, 
        FString NewName 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static void BreakOptional_new_name(const FGrpcSroCharacterEditCharacterRequestOptional_new_name& Optional_new_name, EGrpcSroCharacterEditCharacterRequestOptional_new_name& Optional_new_nameCase, 
        FString& NewName 
    );
};

UCLASS()
class UGrpcSroCharacterEditCharacterRequestOptional_genderHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static FGrpcSroCharacterEditCharacterRequestOptional_gender MakeOptional_gender(EGrpcSroCharacterEditCharacterRequestOptional_gender Optional_genderCase, 
        FString Gender 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static void BreakOptional_gender(const FGrpcSroCharacterEditCharacterRequestOptional_gender& Optional_gender, EGrpcSroCharacterEditCharacterRequestOptional_gender& Optional_genderCase, 
        FString& Gender 
    );
};

UCLASS()
class UGrpcSroCharacterEditCharacterRequestOptional_realmHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static FGrpcSroCharacterEditCharacterRequestOptional_realm MakeOptional_realm(EGrpcSroCharacterEditCharacterRequestOptional_realm Optional_realmCase, 
        FString Realm 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static void BreakOptional_realm(const FGrpcSroCharacterEditCharacterRequestOptional_realm& Optional_realm, EGrpcSroCharacterEditCharacterRequestOptional_realm& Optional_realmCase, 
        FString& Realm 
    );
};

UCLASS()
class UGrpcSroCharacterEditCharacterRequestOptional_play_timeHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static FGrpcSroCharacterEditCharacterRequestOptional_play_time MakeOptional_play_time(EGrpcSroCharacterEditCharacterRequestOptional_play_time Optional_play_timeCase, 
        FUInt64 PlayTime 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static void BreakOptional_play_time(const FGrpcSroCharacterEditCharacterRequestOptional_play_time& Optional_play_time, EGrpcSroCharacterEditCharacterRequestOptional_play_time& Optional_play_timeCase, 
        FUInt64& PlayTime 
    );
};

UCLASS()
class UGrpcSroCharacterEditCharacterRequestOptional_locationHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static FGrpcSroCharacterEditCharacterRequestOptional_location MakeOptional_location(EGrpcSroCharacterEditCharacterRequestOptional_location Optional_locationCase, 
        FGrpcSroLocation Location 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static void BreakOptional_location(const FGrpcSroCharacterEditCharacterRequestOptional_location& Optional_location, EGrpcSroCharacterEditCharacterRequestOptional_location& Optional_locationCase, 
        FGrpcSroLocation& Location 
    );
};

UCLASS()
class UGrpcSroCharacterEditCharacterRequestOptional_dimensionHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static FGrpcSroCharacterEditCharacterRequestOptional_dimension MakeOptional_dimension(EGrpcSroCharacterEditCharacterRequestOptional_dimension Optional_dimensionCase, 
        FGrpcSroGamebackendDimensionTarget Dimension 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroCharacter", meta=(BlueprintThreadSafe))
    static void BreakOptional_dimension(const FGrpcSroCharacterEditCharacterRequestOptional_dimension& Optional_dimension, EGrpcSroCharacterEditCharacterRequestOptional_dimension& Optional_dimensionCase, 
        FGrpcSroGamebackendDimensionTarget& Dimension 
    );
};
