//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcService.h"
#include "SSroChat/ChatClient.h"
#include "ChatService.generated.h"

class UTurboLinkGrpcManager;

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UChatService : public UGrpcService
{
	GENERATED_BODY()
public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual void Connect() override;
	
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual EGrpcServiceState GetServiceState() const override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	UChatServiceClient* MakeClient();

private:
	virtual void Shutdown() override;

	UPROPERTY()
	UChatServiceClient* InnerClient; 
public:
	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcSroChatChatMessage& Response)> FConnectChannelResponseLambda;
	typedef TFunction<void()> FConnectChannelFinishLambda;
	void CallConnectChannel(const FGrpcSroChatChatChannelTarget& Request, FConnectChannelResponseLambda ResponseLambda, FConnectChannelFinishLambda FinishLambda, TMap<FString, FString>& MetaData);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcSroChatChatMessage& Response)> FConnectDirectMessageResponseLambda;
	typedef TFunction<void()> FConnectDirectMessageFinishLambda;
	void CallConnectDirectMessage(const FGrpcSroCharacterCharacterTarget& Request, FConnectDirectMessageResponseLambda ResponseLambda, FConnectDirectMessageFinishLambda FinishLambda, TMap<FString, FString>& MetaData);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response)> FSendChatMessageResponseLambda;
	void CallSendChatMessage(const FGrpcSroChatSendChatMessageRequest& Request, FSendChatMessageResponseLambda ResponseLambda, TMap<FString, FString>& MetaData);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response)> FSendDirectMessageResponseLambda;
	void CallSendDirectMessage(const FGrpcSroChatSendDirectMessageRequest& Request, FSendDirectMessageResponseLambda ResponseLambda, TMap<FString, FString>& MetaData);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcSroChatChatChannel& Response)> FGetChannelResponseLambda;
	void CallGetChannel(const FGrpcSroChatChatChannelTarget& Request, FGetChannelResponseLambda ResponseLambda, TMap<FString, FString>& MetaData);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcSroChatChatChannels& Response)> FAllChatChannelsResponseLambda;
	void CallAllChatChannels(const FGrpcGoogleProtobufEmpty& Request, FAllChatChannelsResponseLambda ResponseLambda, TMap<FString, FString>& MetaData);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response)> FCreateChannelResponseLambda;
	void CallCreateChannel(const FGrpcSroChatCreateChannelMessage& Request, FCreateChannelResponseLambda ResponseLambda, TMap<FString, FString>& MetaData);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response)> FDeleteChannelResponseLambda;
	void CallDeleteChannel(const FGrpcSroChatChatChannelTarget& Request, FDeleteChannelResponseLambda ResponseLambda, TMap<FString, FString>& MetaData);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response)> FEditChannelResponseLambda;
	void CallEditChannel(const FGrpcSroChatUpdateChatChannelRequest& Request, FEditChannelResponseLambda ResponseLambda, TMap<FString, FString>& MetaData);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcSroChatChatChannels& Response)> FGetAuthorizedChatChannelsResponseLambda;
	void CallGetAuthorizedChatChannels(const FGrpcSroCharacterCharacterTarget& Request, FGetAuthorizedChatChannelsResponseLambda ResponseLambda, TMap<FString, FString>& MetaData);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response)> FUpdateUserChatChannelAuthorizationsResponseLambda;
	void CallUpdateUserChatChannelAuthorizations(const FGrpcSroChatRequestChatChannelAuthChange& Request, FUpdateUserChatChannelAuthorizationsResponseLambda ResponseLambda, TMap<FString, FString>& MetaData);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response)> FSetUserChatChannelAuthorizationsResponseLambda;
	void CallSetUserChatChannelAuthorizations(const FGrpcSroChatRequestSetChannelAuth& Request, FSetUserChatChannelAuthorizationsResponseLambda ResponseLambda, TMap<FString, FString>& MetaData);

public:
	class Private;
	Private* const d = nullptr;

public:
	UChatService();
	virtual ~UChatService();
};

