//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "SGoogleApi/AnnotationsMessage.h"
#include "SGoogleProtobuf/EmptyMessage.h"
#include "SSroCharacter/CharacterMessage.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "ChatMessage.generated.h"

UENUM(BlueprintType, meta = (DisplayName="SroChat.UpdateChatChannelRequest.Optional_name", ScriptName="EGrpcSroChatUpdateChatChannelRequestOptional_name"))
enum class EGrpcSroChatUpdateChatChannelRequestOptional_name : uint8
{
    Name=0,
};

UENUM(BlueprintType, meta = (DisplayName="SroChat.UpdateChatChannelRequest.Optional_dimension", ScriptName="EGrpcSroChatUpdateChatChannelRequestOptional_dimension"))
enum class EGrpcSroChatUpdateChatChannelRequestOptional_dimension : uint8
{
    Dimension=0,
};

USTRUCT(BlueprintType, meta = (DisplayName="SroChat.RequestSetChannelAuth"))
struct FGrpcSroChatRequestSetChannelAuth : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroCharacterCharacterTarget Character;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FUInt64> Ids;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroChat.RequestChatChannelAuthChange"))
struct FGrpcSroChatRequestChatChannelAuthChange : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroCharacterCharacterTarget Character;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Add = false;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FUInt64> Ids;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroChat.ChatChannel"))
struct FGrpcSroChatChatChannel : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt64 Id = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Dimension = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroChat.ChatChannels"))
struct FGrpcSroChatChatChannels : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcSroChatChatChannel> Channels;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroChat.CreateChannelMessage"))
struct FGrpcSroChatCreateChannelMessage : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Dimension = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroChat.ChatChannelTarget"))
struct FGrpcSroChatChatChannelTarget : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt64 Id = 0;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroChat.ChatMessage"))
struct FGrpcSroChatChatMessage : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Message = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString CharacterName = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroChat.SendChatMessageRequest"))
struct FGrpcSroChatSendChatMessageRequest : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt64 ChannelId = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroChatChatMessage ChatMessage;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroChat.SendDirectMessageRequest"))
struct FGrpcSroChatSendDirectMessageRequest : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroCharacterCharacterTarget Target;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroChatChatMessage ChatMessage;
};

USTRUCT(BlueprintType, meta = (DisplayName="SroChat.UpdateChatChannelRequest.Optional_name",
    HasNativeMake = "TurboLinkGrpc.GrpcSroChatUpdateChatChannelRequestOptional_nameHelperLibrary.MakeOptional_name",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroChatUpdateChatChannelRequestOptional_nameHelperLibrary.BreakOptional_name"))
struct FGrpcSroChatUpdateChatChannelRequestOptional_name : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroChatUpdateChatChannelRequestOptional_name Optional_nameCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroChat.UpdateChatChannelRequest.Optional_dimension",
    HasNativeMake = "TurboLinkGrpc.GrpcSroChatUpdateChatChannelRequestOptional_dimensionHelperLibrary.MakeOptional_dimension",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroChatUpdateChatChannelRequestOptional_dimensionHelperLibrary.BreakOptional_dimension"))
struct FGrpcSroChatUpdateChatChannelRequestOptional_dimension : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcSroChatUpdateChatChannelRequestOptional_dimension Optional_dimensionCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Dimension = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="SroChat.UpdateChatChannelRequest"))
struct FGrpcSroChatUpdateChatChannelRequest : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt64 ChannelId = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroChatUpdateChatChannelRequestOptional_name Optional_name;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcSroChatUpdateChatChannelRequestOptional_dimension Optional_dimension;
};

UCLASS()
class UGrpcSroChatUpdateChatChannelRequestOptional_nameHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroChat", meta=(BlueprintThreadSafe))
    static FGrpcSroChatUpdateChatChannelRequestOptional_name MakeOptional_name(EGrpcSroChatUpdateChatChannelRequestOptional_name Optional_nameCase, 
        FString Name 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroChat", meta=(BlueprintThreadSafe))
    static void BreakOptional_name(const FGrpcSroChatUpdateChatChannelRequestOptional_name& Optional_name, EGrpcSroChatUpdateChatChannelRequestOptional_name& Optional_nameCase, 
        FString& Name 
    );
};

UCLASS()
class UGrpcSroChatUpdateChatChannelRequestOptional_dimensionHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|SroChat", meta=(BlueprintThreadSafe))
    static FGrpcSroChatUpdateChatChannelRequestOptional_dimension MakeOptional_dimension(EGrpcSroChatUpdateChatChannelRequestOptional_dimension Optional_dimensionCase, 
        FString Dimension 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|SroChat", meta=(BlueprintThreadSafe))
    static void BreakOptional_dimension(const FGrpcSroChatUpdateChatChannelRequestOptional_dimension& Optional_dimension, EGrpcSroChatUpdateChatChannelRequestOptional_dimension& Optional_dimensionCase, 
        FString& Dimension 
    );
};
