//Generated by TurboLink CodeGenerator, do not edit!
#include "ConnectionService_Private.h"

void UConnectionServiceConnectGameServerLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroGamebackendConnectGameServerResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnConnectGameServerResponse.RemoveDynamic(this, &UConnectionServiceConnectGameServerLambdaWrapper::OnResponse);
}

void UConnectionServiceVerifyConnectLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroCharacterCharacterDetails& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnVerifyConnectResponse.RemoveDynamic(this, &UConnectionServiceVerifyConnectLambdaWrapper::OnResponse);
}

void UConnectionServiceTransferPlayerLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroGamebackendConnectGameServerResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnTransferPlayerResponse.RemoveDynamic(this, &UConnectionServiceTransferPlayerLambdaWrapper::OnResponse);
}

void UConnectionServiceIsPlayingLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroGamebackendConnectionStatus& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnIsPlayingResponse.RemoveDynamic(this, &UConnectionServiceIsPlayingLambdaWrapper::OnResponse);
}

