//Generated by TurboLink CodeGenerator, do not edit!
#include "ConnectionContext.h"
#include "SSroGamebackend/ConnectionClient.h"
#include "ConnectionService_Private.h"
#include "ConnectionMarshaling.h"
#include "SGoogleApi/AnnotationsMarshaling.h"
#include "SSroCharacter/CharacterMarshaling.h"
#include "SSro/GlobalsMarshaling.h"
#include "TurboLinkGrpcManager.h"

GrpcContext_ConnectionService_ConnectGameServer::GrpcContext_ConnectionService_ConnectGameServer(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_ConnectionService_ConnectGameServer::Call(const FGrpcSroCharacterCharacterTarget& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::sro::character::CharacterTarget rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UConnectionService* service = (UConnectionService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncConnectGameServer(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_ConnectionService_ConnectGameServer::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::sro::gamebackend::ConnectGameServerResponse* _RpcResponse) 
		{
			UConnectionServiceClient* client = (UConnectionServiceClient*)(this->Client);
			if (!(client->OnConnectGameServerResponse.IsBound())) return;

			FGrpcSroGamebackendConnectGameServerResponse response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnConnectGameServerResponse.Broadcast(Handle, _Result, response);
		}
	);
}

GrpcContext_ConnectionService_VerifyConnect::GrpcContext_ConnectionService_VerifyConnect(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_ConnectionService_VerifyConnect::Call(const FGrpcSroGamebackendVerifyConnectRequest& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::sro::gamebackend::VerifyConnectRequest rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UConnectionService* service = (UConnectionService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncVerifyConnect(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_ConnectionService_VerifyConnect::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::sro::character::CharacterDetails* _RpcResponse) 
		{
			UConnectionServiceClient* client = (UConnectionServiceClient*)(this->Client);
			if (!(client->OnVerifyConnectResponse.IsBound())) return;

			FGrpcSroCharacterCharacterDetails response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnVerifyConnectResponse.Broadcast(Handle, _Result, response);
		}
	);
}

GrpcContext_ConnectionService_TransferPlayer::GrpcContext_ConnectionService_TransferPlayer(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_ConnectionService_TransferPlayer::Call(const FGrpcSroGamebackendTransferPlayerRequest& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::sro::gamebackend::TransferPlayerRequest rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UConnectionService* service = (UConnectionService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncTransferPlayer(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_ConnectionService_TransferPlayer::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::sro::gamebackend::ConnectGameServerResponse* _RpcResponse) 
		{
			UConnectionServiceClient* client = (UConnectionServiceClient*)(this->Client);
			if (!(client->OnTransferPlayerResponse.IsBound())) return;

			FGrpcSroGamebackendConnectGameServerResponse response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnTransferPlayerResponse.Broadcast(Handle, _Result, response);
		}
	);
}

GrpcContext_ConnectionService_IsPlaying::GrpcContext_ConnectionService_IsPlaying(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_ConnectionService_IsPlaying::Call(const FGrpcSroCharacterCharacterTarget& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::sro::character::CharacterTarget rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UConnectionService* service = (UConnectionService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncIsPlaying(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_ConnectionService_IsPlaying::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::sro::gamebackend::ConnectionStatus* _RpcResponse) 
		{
			UConnectionServiceClient* client = (UConnectionServiceClient*)(this->Client);
			if (!(client->OnIsPlayingResponse.IsBound())) return;

			FGrpcSroGamebackendConnectionStatus response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnIsPlayingResponse.Broadcast(Handle, _Result, response);
		}
	);
}
