//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "SSroGamebackend/ConnectionMessage.h"
#include "TurboLinkGrpcContext.h"
#include "sro/gamebackend/connection.grpc.pb.h"

void GRPC_TO_TURBOLINK(const ::sro::gamebackend::ConnectGameServerResponse* in, FGrpcSroGamebackendConnectGameServerResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGamebackendConnectGameServerResponse* in, ::sro::gamebackend::ConnectGameServerResponse* out);

void GRPC_TO_TURBOLINK(const ::sro::gamebackend::VerifyConnectRequest* in, FGrpcSroGamebackendVerifyConnectRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGamebackendVerifyConnectRequest* in, ::sro::gamebackend::VerifyConnectRequest* out);

void GRPC_TO_TURBOLINK(const ::sro::gamebackend::ConnectionStatus* in, FGrpcSroGamebackendConnectionStatus* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGamebackendConnectionStatus* in, ::sro::gamebackend::ConnectionStatus* out);

void GRPC_TO_TURBOLINK(const ::sro::gamebackend::TransferPlayerRequest* in, FGrpcSroGamebackendTransferPlayerRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGamebackendTransferPlayerRequest* in, ::sro::gamebackend::TransferPlayerRequest* out);

typedef grpc::ClientAsyncResponseReader<::sro::gamebackend::ConnectGameServerResponse> ConnectionService_ConnectGameServer_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::sro::character::CharacterDetails> ConnectionService_VerifyConnect_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::sro::gamebackend::ConnectGameServerResponse> ConnectionService_TransferPlayer_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::sro::gamebackend::ConnectionStatus> ConnectionService_IsPlaying_ReaderWriter;
