//Generated by TurboLink CodeGenerator, do not edit!
#pragma once

#include "SSroGamebackend/ServermanagerService.h"
#include "TurboLinkGrpcManager_Private.h"
#include "sro/gamebackend/servermanager.grpc.pb.h"
#include "ServermanagerService_Private.generated.h"

class UServerManagerService::Private
{
public:
	std::shared_ptr<UTurboLinkGrpcManager::Private::ServiceChannel> Channel;
	std::unique_ptr<::sro::gamebackend::ServerManagerService::Stub> Stub;
};


UCLASS()
class UServerManagerServiceCreateDimensionLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UServerManagerServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroGamebackendDimension& Response);
public:
	FGrpcContextHandle Handle;
	UServerManagerService::FCreateDimensionResponseLambda ResponseLambda;
};

UCLASS()
class UServerManagerServiceDuplicateDimensionLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UServerManagerServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroGamebackendDimension& Response);
public:
	FGrpcContextHandle Handle;
	UServerManagerService::FDuplicateDimensionResponseLambda ResponseLambda;
};

UCLASS()
class UServerManagerServiceGetDimensionLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UServerManagerServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroGamebackendDimension& Response);
public:
	FGrpcContextHandle Handle;
	UServerManagerService::FGetDimensionResponseLambda ResponseLambda;
};

UCLASS()
class UServerManagerServiceGetAllDimensionLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UServerManagerServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroGamebackendDimensions& Response);
public:
	FGrpcContextHandle Handle;
	UServerManagerService::FGetAllDimensionResponseLambda ResponseLambda;
};

UCLASS()
class UServerManagerServiceEditDimensionLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UServerManagerServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroGamebackendDimension& Response);
public:
	FGrpcContextHandle Handle;
	UServerManagerService::FEditDimensionResponseLambda ResponseLambda;
};

UCLASS()
class UServerManagerServiceDeleteDimensionLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UServerManagerServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response);
public:
	FGrpcContextHandle Handle;
	UServerManagerService::FDeleteDimensionResponseLambda ResponseLambda;
};

UCLASS()
class UServerManagerServiceCreateMapLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UServerManagerServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroGamebackendMap& Response);
public:
	FGrpcContextHandle Handle;
	UServerManagerService::FCreateMapResponseLambda ResponseLambda;
};

UCLASS()
class UServerManagerServiceGetMapLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UServerManagerServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroGamebackendMap& Response);
public:
	FGrpcContextHandle Handle;
	UServerManagerService::FGetMapResponseLambda ResponseLambda;
};

UCLASS()
class UServerManagerServiceGetAllMapsLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UServerManagerServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroGamebackendMaps& Response);
public:
	FGrpcContextHandle Handle;
	UServerManagerService::FGetAllMapsResponseLambda ResponseLambda;
};

UCLASS()
class UServerManagerServiceEditMapLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UServerManagerServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroGamebackendMap& Response);
public:
	FGrpcContextHandle Handle;
	UServerManagerService::FEditMapResponseLambda ResponseLambda;
};

UCLASS()
class UServerManagerServiceDeleteMapLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UServerManagerServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response);
public:
	FGrpcContextHandle Handle;
	UServerManagerService::FDeleteMapResponseLambda ResponseLambda;
};

