//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "SSroGamebackend/ServermanagerMessage.h"
#include "TurboLinkGrpcContext.h"
#include "sro/gamebackend/servermanager.grpc.pb.h"

void GRPC_TO_TURBOLINK(const ::sro::gamebackend::DimensionTarget* in, FGrpcSroGamebackendDimensionTarget* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGamebackendDimensionTarget* in, ::sro::gamebackend::DimensionTarget* out);

void GRPC_TO_TURBOLINK(const ::sro::gamebackend::MapTarget* in, FGrpcSroGamebackendMapTarget* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGamebackendMapTarget* in, ::sro::gamebackend::MapTarget* out);

void GRPC_TO_TURBOLINK(const ::sro::gamebackend::CreateDimensionRequest* in, FGrpcSroGamebackendCreateDimensionRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGamebackendCreateDimensionRequest* in, ::sro::gamebackend::CreateDimensionRequest* out);

void GRPC_TO_TURBOLINK(const ::sro::gamebackend::DuplicateDimensionRequest* in, FGrpcSroGamebackendDuplicateDimensionRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGamebackendDuplicateDimensionRequest* in, ::sro::gamebackend::DuplicateDimensionRequest* out);

void GRPC_TO_TURBOLINK(const ::sro::gamebackend::EditDimensionRequest* in, FGrpcSroGamebackendEditDimensionRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGamebackendEditDimensionRequest* in, ::sro::gamebackend::EditDimensionRequest* out);

void GRPC_TO_TURBOLINK(const ::sro::gamebackend::Dimension* in, FGrpcSroGamebackendDimension* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGamebackendDimension* in, ::sro::gamebackend::Dimension* out);

void GRPC_TO_TURBOLINK(const ::sro::gamebackend::Dimensions* in, FGrpcSroGamebackendDimensions* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGamebackendDimensions* in, ::sro::gamebackend::Dimensions* out);

void GRPC_TO_TURBOLINK(const ::sro::gamebackend::CreateMapRequest* in, FGrpcSroGamebackendCreateMapRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGamebackendCreateMapRequest* in, ::sro::gamebackend::CreateMapRequest* out);

void GRPC_TO_TURBOLINK(const ::sro::gamebackend::Map* in, FGrpcSroGamebackendMap* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGamebackendMap* in, ::sro::gamebackend::Map* out);

void GRPC_TO_TURBOLINK(const ::sro::gamebackend::EditMapRequest* in, FGrpcSroGamebackendEditMapRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGamebackendEditMapRequest* in, ::sro::gamebackend::EditMapRequest* out);

void GRPC_TO_TURBOLINK(const ::sro::gamebackend::Maps* in, FGrpcSroGamebackendMaps* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGamebackendMaps* in, ::sro::gamebackend::Maps* out);

typedef grpc::ClientAsyncResponseReader<::sro::gamebackend::Dimension> ServerManagerService_CreateDimension_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::sro::gamebackend::Dimension> ServerManagerService_DuplicateDimension_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::sro::gamebackend::Dimension> ServerManagerService_GetDimension_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::sro::gamebackend::Dimensions> ServerManagerService_GetAllDimension_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::sro::gamebackend::Dimension> ServerManagerService_EditDimension_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::google::protobuf::Empty> ServerManagerService_DeleteDimension_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::sro::gamebackend::Map> ServerManagerService_CreateMap_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::sro::gamebackend::Map> ServerManagerService_GetMap_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::sro::gamebackend::Maps> ServerManagerService_GetAllMaps_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::sro::gamebackend::Map> ServerManagerService_EditMap_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::google::protobuf::Empty> ServerManagerService_DeleteMap_ReaderWriter;
